INSERT INTO category_property_assignments (
	category_id,
	property_id,
	is_satisfied,
	reason
)
VALUES
(
	'FinGrp',
	'locally small',
	TRUE,
	'It is a full subcategory of $\mathbf{Grp}$, which is locally small.'
),
(
	'FinGrp',
	'pointed',
	TRUE,
	'The trivial group is a zero object.'
),
(
	'FinGrp',
	'essentially countable',
	TRUE,
	'The underlying set of a finite structure can be chosen to be a subset of $\mathbb{N}$.'
),
(
	'FinGrp',
	'epi-regular',
	TRUE,
	'This holds since every epimorphism is surjective (see below), and a surjective homomorphism $A \to B$ is the coequalizer of its kernel pair $A \times_B A \rightrightarrows A$.'
),
(
	'FinGrp',
	'mono-regular',
	TRUE,
	'See Prop. 4.2 at the <a href="https://ncatlab.org/nlab/show/regular+monomorphism#Examples" target="_blank">nLab</a>. The proof also works for finite groups.'
),
(
	'FinGrp',
	'coequalizers',
	TRUE,
	'The quotient group of a finite group is still finite.'
),
(
	'FinGrp',
	'Malcev',
	TRUE,
	'A direct argument is possible, but this can also be derived from the observation that $\mathbf{FinGrp}$ is the category of group objects in $(\mathbf{FinSet},\times)$ and Example 2.2.16 in <a href="https://ncatlab.org/nlab/show/Malcev,+protomodular,+homological+and+semi-abelian+categories" target="_blank">Malcev, protomodular, homological and semi-abelian categories</a>.'
),
(
	'FinGrp',
	'regular', 
	TRUE,
	'The category is Malcev and hence finitely complete, and it has all coequalizers. The regular epimorphisms coincide with the surjective group homomorphisms (see below), hence are clearly stable under pullbacks.'
),
(
	'FinGrp',
	'conormal',
	TRUE,
	'Since epimorphisms are surjective (see below), this is the first isomorphism theorem for finite groups.'
),
(
	'FinGrp',
	'ℵ₁-accessible',
	TRUE,
	'The proof works exactly as for the <a href="/category/FinSet">category of finite sets</a>.'
),
(
	'FinGrp',
	'normal',
	FALSE,
	'Every non-normal subgroup of a finite group provides a counterexample.'
),
(
	'FinGrp',
	'cogenerator',
	FALSE,
	'We apply <a href="/lemma/missing_cogenerator">this lemma</a> to the collection of finite simple groups: Any non-trivial homomorphism from a finite simple group to a finite group must be injective, and for every $n \in \mathbb{N}$ there is a finite simple group of size $\geq n$ (for example, the alternating group on $n+5$ elements).'
),
(
	'FinGrp',
	'skeletal',
	FALSE,
	'This is trivial.'
),
(
	'FinGrp',
	'binary copowers',
	FALSE,
	'Assume that $C_2 \sqcup C_2$ exists. This is a finite group, say of order $N$, with two involutions $u,v$ such that for every finite group $G$ with two involutions $a,b$ there is a unique homomorphism $\varphi : C_2 \sqcup C_2 \to G$ with $\varphi(u)=a$ and $\varphi(v)=2$. In particular, when $G$ is generated by $a,b$, then $\mathrm{ord}(G) \leq N$. But then the dihedral group $G := D_N$ of order $2N$ yields a contradiction.'
),
(
	'FinGrp',
	'small',
	FALSE,
	'Even the collection of trivial groups is not small.'
),
(
	'FinGrp',
	'generator',
	FALSE,
	'If $A,B$ are finite groups whose orders are coprime, then we know that $\hom(A,B)$ is trivial. But a generator would admit a non-trivial homomorphism to any other non-trivial finite group.'
),
(
	'FinGrp',
	'countable powers',
	FALSE,
	'If countable powers exist, then by <a href="/lemma/hilberts_hotel">Hilbert''s Hotel</a> there is some object $P$ with $P \cong C_2 \times P$. If $P$ has $n$ elements, this means $n = 2n$, i.e. $n = 0$, a contradiction.'
),
(
	'FinGrp',
	'sequential colimits',
	FALSE,
	'This follows from <a href="/lemma/special_sequential_colimits">this lemma</a>.'
),
(
	'FinGrp',
	'countable',
	FALSE,
	'This is trivial.'
);