INSERT INTO category_property_assignments (
	category_id,
	property_id,
	is_satisfied,
	reason
)
VALUES
(
	'FinGrp',
	'locally small',
	TRUE,
	'It is a full subcategory of $\mathbf{Grp}$, which is locally small.'
),
(
	'FinGrp',
	'pointed',
	TRUE,
	'The trivial group is a zero object.'
),
(
	'FinGrp',
	'essentially small',
	TRUE,
	'The underlying set of a finite structure can be chosen to be a subset of $\mathbb{N}$.'
),
(
	'FinGrp',
	'epi-regular',
	TRUE,
	'This holds since every epimorphism is surjective (see below), and a surjective homomorphism $A \to B$ is the coequalizer of its kernel pair $A \times_B A \rightrightarrows A$.'
),
(
	'FinGrp',
	'mono-regular',
	TRUE,
	'See Prop. 4.2 at the <a href="https://ncatlab.org/nlab/show/regular+monomorphism#Examples" target="_blank">nLab</a>. The proof also works for finite groups.'
),
(
	'FinGrp',
	'coequalizers',
	TRUE,
	'The quotient group of a finite group is still finite.'
),
(
	'FinGrp',
	'Malcev',
	TRUE,
	'A direct argument is possible, but this can also be derived from the observation that $\mathbf{FinGrp}$ is the category of group objects in $(\mathbf{FinSet},\times)$ and Example 2.2.16 in <a href="https://ncatlab.org/nlab/show/Malcev,+protomodular,+homological+and+semi-abelian+categories" target="_blank">Malcev, protomodular, homological and semi-abelian categories</a>.'
),
(
	'FinGrp',
	'regular', 
	TRUE,
	'The category is Malcev and hence finitely complete, and it has all coequalizers. The regular epimorphisms coincide with the surjective group homomorphisms (see below), hence are clearly stable under pullbacks.'
),
(
	'FinGrp',
	'disjoint finite products',
	TRUE,
	'This can be deduced from the fact that $\mathbf{Grp}$ has disjoint finite products. But we can also show it directly: Clearly, the projections $A \times B \to A$ are surjective, hence epimorphisms. To show that $A \sqcup_{A \times B} B$ is trivial, let $C$ be a finite group which admits homomorphisms $f : A \to C$, $g : B \to C$ with $f(p_1(a,b))=g(p_2(a,b))$ for all $(a,b) \in A \times B$, i.e. $f(a)=g(b)$. Then $f(a)=g(1)=1$, and likewise $g(b)=1$, so that both $f$ and $g$ are trivial.'
),
(
	'FinGrp',
	'subobject classifier',
	FALSE,
	'If there was a subgroup classifier $\Omega$, every subgroup of any finite group would be the kernel of a homomorphism to $\Omega$. But not every subgroup is normal.'
),
(
	'FinGrp',
	'cogenerator',
	FALSE,
	'Assume there is a finite group $Q$ that cogenerates. Take a simple group $G$ larger than $Q$ (w.r.t. cardinalities), for example an alternating group. Then every homomorphism $G \to Q$ is trivial. Since $Q$ cogenerates, $G$ is trivial, a contradiction.'
),
(
	'FinGrp',
	'skeletal',
	FALSE,
	'This is trivial.'
),
(
	'FinGrp',
	'binary copowers',
	FALSE,
	'Assume that $C_2 \sqcup C_2$ exists. This is a finite group, say of order $N$, with two involutions $u,v$ such that for every finite group $G$ with two involutions $a,b$ there is a unique homomorphism $\varphi : C_2 \sqcup C_2 \to G$ with $\varphi(u)=a$ and $\varphi(v)=2$. In particular, when $G$ is generated by $a,b$, then $\mathrm{ord}(G) \leq N$. But then the dihedral group $G := D_N$ of order $2N$ yields a contradiction.'
),
(
	'FinGrp',
	'small',
	FALSE,
	'Even the collection of trivial groups is not small.'
),
(
	'FinGrp',
	'generator',
	FALSE,
	'If $A,B$ are finite groups whose orders are coprime, then we know that $\hom(A,B)$ is trivial. But a generator would admit a non-trivial homomorphism to any other non-trivial finite group.'
),
(
	'FinGrp',
	'countable powers',
	FALSE,
	'Assume that the power $P := (C_2)^{\mathbb{N}}$ exists. Since products are associative and finite products exist, we conclude $P \cong C_2 \times P$. If $P$ has $n$ elements, this means $n = 2n$, i.e. $n = 0$, a contradiction.'
),
(
	'FinGrp',
	'sequential colimits',
	FALSE,
	'Let $G$ be a non-trivial finite group. We prove that the sequence of homomorphisms $1 \to G \to G^2 \to G^3 \to \cdots$ defined by $(x_1,\dotsc,x_n) \mapsto (x_1,\dotsc,x_n,1)$ has no colimit. Assume that $(G^n \to C)_{n \in \mathbb{N}}$ is a colimit. If $m \in \mathbb{N}$ is fixed, we have homomorphisms $G^n \to G^m$ for $n \in \mathbb{N}$ defined as the inclusion for $n \leq m$ and as the projection for $n \geq m$. They are compatible, hence yield a homomorphism $C \to G^m$. By construction, $G^m \to C \to G^m$ is the identity. In particular, $C \to G^m$ is surjective. But then $C$ has at least $2^m$ elements, for every $m$, which is a contradiction.'
);