import type { PreCategory } from '$lib/commons/types'

/**
 * Each category has the following data:
 * - id (must be defined in categoryIDs.ts)
 * - name
 * - notation (LaTeX)
 * - nlab_link (optional, add only if available)
 * - objects (description of the objects, may contain LaTeX)
 * - morphisms (description of the morphisms, may contain LaTeX)
 * - description (optional, keep it short)
 * - related (optional list of related categories, referred to by their IDs)
 * - tags (required, must have only allowed tags)
 * - properties (list of essential properties, non-redundant, must be registered)
 * - non_properties (list of essential non-properties, non-redundant, must be registered)
 * - monomorphisms (optional description of monomorphisms, may contain LaTeX)
 * - epimorphisms (optional description of epimorphisms, may contain LaTeX)
 */
export const categories: readonly Readonly<PreCategory>[] = [
	{
		id: 'Set',
		name: 'category of sets',
		notation: '$\\mathbf{Set}$',
		nlab_link: 'https://ncatlab.org/nlab/show/Set',
		objects: 'sets',
		morphisms: 'maps',
		description:
			'The category of sets plays a fundamental role in category theory. Due to the Yoneda embedding, many results about general categories can be reduced to the category of sets. It is also usually the first example of a category that one encounters.',
		related: ['FinSet'],
		tags: ['basic', 'set theory', 'well-behaved'],
		properties: ['Grothendieck topos', 'finitary algebraic'],
		non_properties: ['strict terminal object'],
		monomorphisms: 'injective maps',
		epimorphisms: 'surjective maps',
	},
	{
		id: 'Ab',
		name: 'category of abelian groups',
		notation: '$\\mathbf{Ab}$',
		nlab_link: 'https://ncatlab.org/nlab/show/Ab',
		objects: 'abelian groups',
		morphisms: 'group homomorphisms',
		description: 'This is the prototype of an abelian category.',
		related: ['Grp', 'R-Mod'],
		tags: ['basic', 'algebra', 'well-behaved'],
		properties: ['abelian', 'finitary algebraic'],
		non_properties: ['split abelian'],
		monomorphisms: 'injective homomorphisms',
		epimorphisms: 'surjective homomorphisms',
	},
	{
		id: 'Top',
		name: 'category of topological spaces',
		notation: '$\\mathbf{Top}$',
		nlab_link: 'https://ncatlab.org/nlab/show/Top',
		objects: 'topological spaces',
		morphisms: 'continuous functions',
		description: 'This is the most basic category of geometric objects.',
		tags: ['basic', 'topology', 'well-behaved'],
		properties: [
			'locally small',
			'complete',
			'cocomplete',
			'well-powered',
			'well-copowered',
			'infinitary distributive',
			'generator',
			'disjoint coproducts',
		],
		non_properties: [
			'cartesian closed',
			'locally presentable',
			'strict terminal object',
			'balanced',
			'cogenerator',
			'exact filtered colimits',
		],
		monomorphisms: 'injective continuous maps',
		epimorphisms: 'surjective continuous maps',
	},
	{
		id: 'Grp',
		name: 'category of groups',
		notation: '$\\mathbf{Grp}$',
		nlab_link: 'https://ncatlab.org/nlab/show/Grp',
		objects: 'groups',
		morphisms: 'group homomorphisms',
		related: ['Ab', 'Mon'],
		tags: ['basic', 'algebra', 'well-behaved'],
		properties: ['pointed', 'finitary algebraic', 'balanced', 'disjoint coproducts'],
		non_properties: ['preadditive', 'subobject classifier', 'cogenerator'],
		monomorphisms: 'injective homomorphisms',
		epimorphisms: 'surjective homomorphisms',
	},
	{
		id: 'Vect',
		name: 'category of vector spaces',
		notation: '$\\mathbf{Vect}_K$',
		nlab_link: 'https://ncatlab.org/nlab/show/Vect',
		objects: 'vector spaces over a field $K$',
		morphisms: 'linear maps',
		description:
			'This is a special case of the category of modules over a ring, where the ring is a field. It is the prototype of a split abelian category.',
		related: ['R-Mod'],
		tags: ['basic', 'algebra', 'well-behaved'],
		properties: ['split abelian', 'finitary algebraic'],
		non_properties: ['trivial'],
		monomorphisms: 'injective linear maps',
		epimorphisms: 'surjective linear maps',
	},
	{
		id: 'Ring',
		name: 'category of rings',
		notation: '$\\mathbf{Ring}$',
		nlab_link: 'https://ncatlab.org/nlab/show/Ring',
		objects: 'rings',
		morphisms: 'ring homomorphisms',
		description: 'Here, rings always have a unit, and homomorphisms preserve them.',
		related: ['CRing', 'Rng'],
		tags: ['basic', 'algebra', 'well-behaved'],
		properties: ['finitary algebraic', 'strict terminal object'],
		non_properties: [
			'strict initial object',
			'balanced',
			'cogenerator',
			'disjoint finite coproducts',
		],
		monomorphisms: 'injective ring homomorphisms',
		epimorphisms: 'are not necessarily surjective',
	},
	{
		id: 'CRing',
		name: 'category of commutative rings',
		notation: '$\\mathbf{CRing}$',
		nlab_link: 'https://ncatlab.org/nlab/show/CRing',
		objects: 'commutative rings',
		morphisms: 'ring homomorphisms',
		related: ['Ring', 'Rng'],
		tags: ['basic', 'algebra', 'well-behaved'],
		properties: ['finitary algebraic', 'strict terminal object'],
		non_properties: [
			'strict initial object',
			'balanced',
			'cogenerator',
			'disjoint finite coproducts',
		],
		monomorphisms: 'injective ring homomorphisms',
		epimorphisms: 'are not necessarily surjective',
	},
	{
		id: 'Rng',
		name: 'category of rngs',
		notation: '$\\mathbf{Rng}$',
		nlab_link: 'https://ncatlab.org/nlab/show/Rng',
		objects: 'rngs, that is, non-unital rings',
		morphisms: 'maps that preserve addition and multiplication',
		related: ['Ring', 'CRing'],
		tags: ['basic', 'algebra', 'well-behaved'],
		properties: ['finitary algebraic', 'pointed', 'disjoint coproducts'],
		non_properties: ['preadditive', 'balanced', 'cogenerator'],
		monomorphisms: 'injective ring homomorphisms',
		epimorphisms: 'are not necessarily surjective',
	},
	{
		id: 'FinSet',
		name: 'category of finite sets',
		notation: '$\\mathbf{FinSet}$',
		nlab_link: 'https://ncatlab.org/nlab/show/FinSet',
		objects: 'finite sets',
		morphisms: 'maps',
		related: ['Set'],
		tags: ['basic', 'set theory', 'well-behaved'],
		properties: [
			'essentially small',
			'locally small',
			'elementary topos',
			'generator',
			'cogenerator',
		],
		non_properties: ['small', 'strict terminal object'],
		monomorphisms: 'injective maps',
		epimorphisms: 'surjective maps',
	},
	{
		id: 'FinAb',
		name: 'category of finite abelian groups',
		notation: '$\\mathbf{FinAb}$',
		nlab_link: 'https://ncatlab.org/nlab/show/finite+abelian+group',
		objects: 'finite abelian groups',
		morphisms: 'group homomorphisms',
		related: ['Ab', 'Abfg'],
		tags: ['basic', 'algebra', 'badly-behaved'],
		properties: ['essentially small', 'abelian', 'self-dual'],
		non_properties: ['small', 'generator', 'split abelian'],
		monomorphisms: 'injective homomorphisms',
		epimorphisms: 'surjective homomorphisms',
	},
	{
		id: 'Abfg',
		name: 'category of finitely generated abelian groups',
		notation: '$\\mathbf{Ab}_{\\mathrm{fg}}$',
		nlab_link: 'https://ncatlab.org/nlab/show/finitely+generated+module',
		objects: 'finitely generated abelian groups',
		morphisms: 'group homomorphisms',
		related: ['Ab', 'FinAb'],
		tags: ['basic', 'algebra', 'badly-behaved'],
		properties: ['essentially small', 'abelian', 'generator'],
		non_properties: ['small', 'cogenerator', 'split abelian'],
		monomorphisms: 'injective homomorphisms',
		epimorphisms: 'surjective homomorphisms',
	},
	{
		id: 'Set*',
		name: 'category of pointed sets',
		notation: '$\\mathbf{Set}_*$',
		nlab_link: 'https://ncatlab.org/nlab/show/pointed+set',
		objects: 'pointed sets',
		morphisms: 'pointed maps',
		description:
			'This is the category of sets with a distinguished element, often called the base point. A map is called pointed when it preserves the base point.',
		tags: ['basic', 'set theory', 'well-behaved'],
		properties: [
			'pointed',
			'finitary algebraic',
			'subobject classifier',
			'cogenerator',
			'disjoint coproducts',
		],
		non_properties: ['preadditive'],
		monomorphisms: 'injective maps',
		epimorphisms: 'surjective maps',
	},
	{
		id: 'sSet',
		name: 'category of simplicial sets',
		notation: '$\\mathbf{sSet}$',
		nlab_link: 'https://ncatlab.org/nlab/show/SimpSet',
		objects:
			'simplicial sets, i.e. functors $\\Delta^{\\mathrm{op}} \\to \\mathbf{Set}$',
		morphisms: 'natural transformations',
		tags: ['basic', 'topology', 'well-behaved'],
		properties: ['Grothendieck topos', 'locally finitely presentable'],
		non_properties: ['strict terminal object'],
		monomorphisms: 'pointwise injective transformations',
		epimorphisms: 'pointwise surjective transformations',
	},
	{
		id: 'Mon',
		name: 'category of monoids',
		notation: '$\\mathbf{Mon}$',
		nlab_link: 'https://ncatlab.org/nlab/show/category+of+monoids',
		objects: 'monoids',
		morphisms: 'monoid homomorphisms',
		related: ['Grp'],
		tags: ['basic', 'algebra', 'well-behaved'],
		properties: ['pointed', 'finitary algebraic', 'disjoint coproducts'],
		non_properties: ['preadditive', 'balanced', 'cogenerator'],
		monomorphisms: 'injective homomorphisms',
		epimorphisms: 'are not necessarily surjective',
	},
	{
		id: 'Pos',
		name: 'category of posets',
		notation: '$\\mathbf{Pos}$',
		nlab_link: 'https://ncatlab.org/nlab/show/Pos',
		objects: 'posets (i.e., partial orders)',
		morphisms: 'order-preserving functions',
		tags: ['basic', 'order theory', 'well-behaved'],
		properties: [
			'locally finitely presentable',
			'cartesian closed',
			'cogenerator',
			'disjoint coproducts',
		],
		non_properties: ['strict terminal object', 'finitary algebraic', 'balanced'],
		monomorphisms: 'injective order-preserving functions',
		epimorphisms: 'surjective order-preserving functions',
	},
	{
		id: '0',
		name: 'empty category',
		notation: '$0$',
		nlab_link: 'https://ncatlab.org/nlab/show/empty+category',
		objects: 'no objects',
		morphisms: 'no morphisms',
		description:
			'This is the category with no objects and no morphisms. It is the initial object in the category of small categories.',
		tags: ['basic', 'badly-behaved'],
		properties: ['preadditive', 'discrete', 'binary products', 'finite'],
		non_properties: ['inhabited'],
		monomorphisms: "there aren't any",
		epimorphisms: "there aren't any",
	},
	{
		id: '1',
		name: 'trivial category',
		notation: '$\\mathbf{1}$',
		nlab_link: 'https://ncatlab.org/nlab/show/terminal+category',
		objects: 'a single object',
		morphisms: 'only the identity morphism',
		description:
			'This is the simplest category, consisting of a single object and only the identity morphism. It is the terminal object in the category of small categories.',
		related: ['2'],
		tags: ['basic', 'well-behaved'],
		properties: ['trivial', 'finite', 'discrete'],
		non_properties: [],
		monomorphisms: 'every morphism',
		epimorphisms: 'every morphism',
	},
	{
		id: '2',
		name: 'discrete category on two objects',
		notation: '$\\mathbf{2}$',
		objects: 'two objects',
		morphisms: 'only the two identity morphisms',
		description:
			'For a more concrete representation, this is the subcategory of $\\mathbf{CRing}$ of the two fields $\\mathbb{F}_2$ and $\\mathbb{F}_3$.',
		related: ['1'],
		tags: ['basic', 'badly-behaved'],
		properties: ['discrete', 'finite', 'inhabited'],
		non_properties: ['connected'],
		monomorphisms: 'every morphism',
		epimorphisms: 'every morphism',
	},
	{
		id: 'I',
		name: 'interval category',
		notation: '$I$',
		nlab_link: 'https://ncatlab.org/nlab/show/interval+category',
		objects: '0,1',
		morphisms: 'the two identities and a single morphism from 0 to 1',
		description:
			'This is the category with two objects and a single non-identity morphism between them. It has the property that functors out of this category are the same as morphisms.',
		tags: ['basic', 'well-behaved'],
		properties: ['finitary algebraic', 'self-dual', 'finite', 'cartesian closed'],
		non_properties: ['subobject classifier'],
		monomorphisms: 'every morphism',
		epimorphisms: 'every morphism',
	},
	{
		id: 'M-Set',
		name: 'category of M-sets',
		notation: '$M{-}\\mathbf{Set}$',
		nlab_link: 'https://ncatlab.org/nlab/show/MSet',
		objects: 'sets with a left action of a monoid $M$',
		morphisms:
			'maps that are compatible with the $M$-action, meaning $f(m \\cdot x)=m \\cdot f(x)$, also called $M$-maps',
		description:
			'Here, $M$ can be any monoid. But the most important special case is that of a group.',
		tags: ['basic', 'algebra', 'geometry', 'well-behaved'],
		properties: ['Grothendieck topos', 'finitary algebraic'],
		non_properties: ['strict terminal object'],
		monomorphisms: 'injective $M$-maps',
		epimorphisms: 'surjective $M$-maps',
	},
	{
		id: 'R-Mod',
		name: 'category of left R-modules',
		notation: '$R{-}\\mathbf{Mod}$',
		nlab_link: 'https://ncatlab.org/nlab/show/module',
		objects: 'left $R$-modules',
		morphisms: '$R$-linear maps',
		description:
			"This is the category of left modules over a ring $R$. It is the prototype of an abelian category. The category of right modules is the same with the opposite ring $R^{\\mathrm{op}}$, hence not listed here. The non-properties refer to the case that the ring is non-trivial, since for the trivial ring we get a trivial category which has all properties anyway. The category $R{-}\\mathbf{Mod}$ is split abelian iff $R$ is a semisimple ring, so usually it isn't the case, which is why we have negated this property here.",
		related: ['Ab'],
		tags: ['basic', 'algebra', 'well-behaved'],
		properties: ['abelian', 'finitary algebraic'],
		non_properties: ['split abelian'],
		monomorphisms: 'injective $R$-linear maps',
		epimorphisms: 'surjective $R$-linear maps',
	},
	{
		id: 'Met',
		name: 'category of metric spaces',
		notation: '$\\mathbf{Met}$',
		nlab_link: 'https://ncatlab.org/nlab/show/Met',
		objects: 'metric spaces',
		morphisms:
			'non-expansive maps $f$, meaning $d(f(x),f(y)) \\leq d(x,y)$ for all $x,y$',
		related: ['Met_oo'],
		tags: ['basic', 'geometry', 'badly-behaved'],
		properties: [
			'locally small',
			'well-powered',
			'well-copowered',
			'equalizers',
			'finite products',
			'coequalizers',
			'filtered colimits',
			'strict initial object',
			'generator',
			'cogenerator',
		],
		non_properties: [
			'products',
			'finite coproducts',
			'strict terminal object',
			'balanced',
			'cartesian closed',
			'essentially small',
		],
		monomorphisms: 'injective non-expansive maps',
		epimorphisms: 'are not necessarily surjective. TODO: make this more precise',
	},
	{
		id: 'Met_oo',
		name: 'complete category of metric spaces',
		notation: '$\\mathbf{Met}_{\\infty}$',
		nlab_link: 'https://ncatlab.org/nlab/show/Met',
		objects:
			'metric spaces, where the metric is allowed to assume the value $\\infty$',
		morphisms:
			'non-expansive maps $f$, meaning $d(f(x),f(y)) \\leq d(x,y)$ for all $x,y$',
		description:
			'The fact that we allow $\\infty$ means that universal constructions work much better.',
		related: ['Met'],
		tags: ['basic', 'geometry', 'well-behaved'],
		properties: [
			'locally small',
			'well-powered',
			'well-copowered',
			'complete',
			'cocomplete',
			'infinitary distributive',
			'generator',
			'cogenerator',
			'disjoint coproducts',
		],
		non_properties: [
			'strict terminal object',
			'balanced',
			'finitary algebraic',
			'cartesian closed',
		],
		monomorphisms: 'injective non-expansive maps',
		epimorphisms: 'are not necessarily surjective. TODO: make this more precise',
	},
	{
		id: 'Man',
		name: 'category of smooth manifolds',
		notation: '$\\mathbf{Man}$',
		nlab_link: 'https://ncatlab.org/nlab/show/Diff',
		objects: 'smooth manifolds',
		morphisms: 'smooth maps',
		description:
			'Here, a smooth manifold is assumed to be finite-dimensional, Hausdorff, and second-countable.',
		tags: ['geometry', 'topology', 'badly-behaved'],
		properties: [
			'locally small',
			'well-powered',
			'well-copowered',
			'distributive',
			'generator',
			'disjoint finite coproducts',
		],
		non_properties: [
			'essentially small',
			'products',
			'coproducts',
			'cartesian closed',
			'coequalizers',
			'equalizers',
			'strict terminal object',
			'balanced',
		],
		monomorphisms: 'injective smooth maps',
		epimorphisms: 'are not necessarily surjective. TODO: make this more precise',
	},
	{
		id: 'Meas',
		name: 'category of measurable spaces',
		notation: '$\\mathbf{Meas}$',
		nlab_link: 'https://ncatlab.org/nlab/show/Meas',
		objects: 'measurable spaces',
		morphisms: 'measurable maps',
		description:
			'Limits and colimits can be constructed in the same way as for topological spaces.',
		tags: ['basic', 'measure theory', 'well-behaved'],
		properties: [
			'locally small',
			'well-powered',
			'well-copowered',
			'complete',
			'cocomplete',
			'infinitary distributive',
			'generator',
			'cogenerator',
			'disjoint coproducts',
		],
		non_properties: ['cartesian closed', 'strict terminal object', 'balanced'],
		monomorphisms: 'injective measurable maps',
		epimorphisms: 'surjective measurable maps',
	},
	{
		id: 'N',
		name: 'partial order of natural numbers',
		notation: '$(\\mathbb{N},\\leq)$',
		objects: 'natural numbers $0, 1, 2, \\dotsc$',
		morphisms: 'a unique morphism $n \\to m$ if $n \\leq m$',
		description:
			'This can also be seen as the path category of the infinite linear graph $\\bullet \\to \\bullet \\to \\bullet \\to \\cdots$.',
		related: ['On'],
		tags: ['basic'],
		properties: [
			'small',
			'finitely cocomplete',
			'binary products',
			'thin',
			'wide pullbacks',
		],
		non_properties: ['cocomplete', 'terminal object', 'finite'],
		monomorphisms: 'every morphism',
		epimorphisms: 'every morphism',
	},
	{
		id: 'Cat',
		name: 'category of small categories',
		notation: '$\\mathbf{Cat}$',
		nlab_link: 'https://ncatlab.org/nlab/show/Cat',
		objects: 'small categories',
		morphisms: 'functors',
		description:
			'This is the category of small categories and functors between them. It is the prototype of a 2-category, but here we only treat it as a 1-category.',
		tags: ['intermediate', 'category theory', 'well-behaved'],
		properties: [
			'cartesian closed',
			'locally finitely presentable',
			'disjoint coproducts',
		],
		non_properties: [
			'strict terminal object',
			'finitary algebraic',
			'balanced',
			'cogenerator',
		],
		monomorphisms: 'faithful functors that are injective on objects',
		epimorphisms:
			"are surjective on objects, but not necessarily on morphisms. Isbell's zigzag theorem gives a precise characterization.",
	},
	{
		id: 'On',
		name: 'partial order of ordinal numbers',
		notation: '$(\\mathbf{On},\\leq)$',
		objects: 'ordinal numbers',
		morphisms: 'a unique morphism $\\alpha \\to \\beta$ if $\\alpha \\leq \\beta$',
		description: 'This is a large variant of the partial order of natural numbers.',
		related: ['N'],
		tags: ['intermediate', 'artificial', 'set theory'],
		properties: [
			'thin',
			'locally small',
			'cocomplete',
			'binary products',
			'wide pullbacks',
			'well-powered',
		],
		non_properties: ['terminal object', 'well-copowered'],
		monomorphisms: 'every morphism',
		epimorphisms: 'every morphism',
	},
	{
		id: 'LRS',
		name: 'category of locally ringed spaces',
		notation: '$\\mathbf{LRS}$',
		objects: 'locally ringed spaces',
		morphisms:
			'morphisms of locally ringed spaces, thus consisting of a continuous map and a homomorphism of sheaves that induces local ring homomorphisms in the stalks',
		related: ['Sch'],
		tags: ['intermediate', 'algebraic geometry', 'well-behaved'],
		properties: [
			'locally small',
			'complete',
			'cocomplete',
			'well-powered',
			'well-copowered',
			'infinitary distributive',
			'disjoint coproducts',
		],
		non_properties: ['cartesian closed', 'strict terminal object'],
	},
	{
		id: 'Sch',
		name: 'category of schemes',
		notation: '$\\mathbf{Sch}$',
		objects: 'schemes',
		morphisms: 'morphism of locally ringed spaces',
		related: ['LRS', 'Z'],
		tags: ['intermediate', 'algebraic geometry', 'badly-behaved'],
		properties: [
			'locally small',
			'finitely complete',
			'well-powered',
			'infinitary distributive',
			'disjoint coproducts',
		],
		non_properties: [
			'essentially small',
			'coequalizers',
			'products',
			'cartesian closed',
			'strict terminal object',
		],
		monomorphisms: 'cf. EGA IV, 17.2.6',
	},
	{
		id: 'Fld',
		name: 'category of fields',
		notation: '$\\mathbf{Fld}$',
		nlab_link: 'https://ncatlab.org/nlab/show/Field',
		objects: 'fields',
		morphisms: 'field homomorphisms (i.e., ring homomorphisms)',
		description: 'This is a typical example of a bad category of good objects.',
		tags: ['basic', 'algebra', 'badly-behaved'],
		properties: [
			'locally small',
			'filtered colimits',
			'connected limits',
			'inhabited',
			'left cancellative',
			'well-powered',
		],
		non_properties: [
			'connected',
			'well-copowered',
			'pushouts',
			'balanced',
			'generator',
			'cogenerator',
		],
		monomorphisms: 'every morphism',
		epimorphisms: 'purely inseparable homomorphisms',
	},
	{
		id: 'FreeAb',
		name: 'category of free abelian groups',
		notation: '$\\mathbf{FreeAb}$',
		objects: 'free abelian groups',
		morphisms: 'group homomorphisms',
		related: ['Ab'],
		tags: ['artificial', 'basic', 'algebra', 'badly-behaved'],
		properties: [
			'additive',
			'well-powered',
			'well-copowered',
			'equalizers',
			'generator',
			'cogenerator',
			'disjoint coproducts',
		],
		non_properties: [
			'essentially small',
			'products',
			'balanced',
			'filtered colimits',
		],
		monomorphisms: 'injective homomorphisms',
		epimorphisms:
			'homomorphisms $f : A \\to B$ with the property that $f(A)$ is not contained in a proper direct summand of $B$.',
	},
	{
		id: 'Z',
		name: 'category of Z-functors',
		notation: '$[\\mathbf{CRing}, \\mathbf{Set}]$',
		objects: 'Z-functors, i.e. functors from commutative rings to sets',
		morphisms: 'natural transformations',
		description:
			'This category is used in functorial algebraic geometry. It also provides a typical example of a functor category that is not locally small, but nevertheless relevant. Most of its properties are directly derived from the category of sets, so other functor categories $[\\mathbf{C}, \\mathbf{Set}]$ for large categories $\\mathbf{C}$ will be similar.',
		related: ['Sch', 'Set'],
		tags: ['intermediate', 'algebraic geometry', 'well-behaved'],
		properties: [
			'complete',
			'cocomplete',
			'balanced',
			'infinitary distributive',
			'exact filtered colimits',
			'disjoint coproducts',
		],
		non_properties: ['locally small', 'strict terminal object'],
		monomorphisms: 'objectwise injective natural transformations',
		epimorphisms: 'objectwise surjective natural transformations',
	},
	{
		id: 'BG',
		name: 'delooping of a group',
		notation: '$BG$',
		nlab_link: 'https://ncatlab.org/nlab/show/delooping',
		objects: 'a single object',
		morphisms: 'the elements of a group $G$',
		description:
			'Every group $G$ yields a groupoid $BG$ with a single object, morphisms given by the elements of $G$, and composition given by the group operation. When $G$ is trivial, then $BG$ is the trivial category. However, in the non-properties below, we refer to the case that $G$ is non-trivial. The non-property "finite" refers to the case that $G$ is "generic" and hence infinite.',
		tags: ['basic', 'algebra', 'category theory', 'badly-behaved'],
		properties: ['small', 'groupoid', 'connected', 'generator'],
		non_properties: ['finite', 'thin', 'zero morphisms'],
		monomorphisms: 'every morphism',
		epimorphisms: 'every morphism',
	},
	{
		id: 'BN',
		name: 'delooping of the additive monoid of natural numbers',
		notation: '$B\\mathbb{N}$',
		objects: 'a single object',
		morphisms: 'the natural numbers, with addition serving as composition',
		description:
			'Every monoid $M$ induces a one-object category $BM$ with morphisms given by the elements of $M$, and composition given by the monoid operation. Some of the properties of this category depend on the specific monoid. In this example, we take the commutative monoid $M = (\\mathbb{N},+,0)$.',
		related: ['BG', 'On+'],
		tags: ['basic', 'algebra', 'category theory', 'badly-behaved'],
		properties: [
			'small',
			'connected',
			'self-dual',
			'generator',
			'pullbacks',
			'left cancellative',
		],
		non_properties: ['finite', 'zero morphisms', 'equalizers', 'filtered colimits'],
		monomorphisms: 'every morphism',
		epimorphisms: 'every morphism',
	},
	{
		id: 'walking_pair',
		name: 'walking parallel pair of morphisms',
		notation: '$\\{0 \\rightrightarrows 1 \\}$',
		nlab_link: 'https://ncatlab.org/nlab/show/walking+structure',
		objects: 'two objects $0$ and $1$',
		morphisms: 'the two identities and two parallel morphisms from $0$ to $1$',
		description:
			"This is the 'walking parallel pair' of morphisms. The name comes from the fact that it consists of two parallel morphisms, and a functor out of this category is the same as a parallel pair of morphisms in the target category.",
		related: ['I'],
		tags: ['artificial', 'category theory', 'badly-behaved'],
		properties: [
			'finite',
			'self-dual',
			'connected',
			'generator',
			'filtered limits',
			'left cancellative',
		],
		non_properties: [
			'initial object',
			'zero morphisms',
			'binary products',
			'equalizers',
			'pullbacks',
		],
		monomorphisms: 'every morphism',
		epimorphisms: 'every morphism',
	},
	{
		id: 'walking_isomorphism',
		name: 'walking isomorphism',
		notation: '$\\{0 \\rightleftarrows 1\\}$',
		nlab_link: 'https://ncatlab.org/nlab/show/walking+isomorphism',
		objects: 'two objects $0$ and $1$',
		morphisms:
			'identities, and two morphisms $0 \\to 1$ and $1 \\to 0$ that are mutually inverse',
		description:
			"This is the 'walking isomorphism' category. The name comes from the fact that it consists of two objects and an isomorphism between them, and a functor out of this category is the same as an isomorphism in the target category. The walking isomorphism is actually equivalent to the trivial category.",
		related: ['I', '1'],
		tags: ['artificial', 'category theory', 'badly-behaved'],
		properties: ['trivial', 'finite'],
		non_properties: ['discrete'],
		monomorphisms: 'every morphism',
		epimorphisms: 'every morphism',
	},
	{
		id: 'Setne',
		name: 'category of non-empty sets',
		notation: '$\\mathbf{Set}_{\\neq \\emptyset}$',
		nlab_link: 'https://ncatlab.org/nlab/show/inhabited+set',
		objects: 'non-empty sets',
		morphisms: 'maps',
		description:
			'This entry demonstrates that removing an object (the empty set) can drastically change the properties of a category. In particular, this category is neither complete nor cocomplete.',
		related: ['Set'],
		tags: ['artificial', 'set theory', 'badly-behaved'],
		properties: [
			'locally small',
			'generator',
			'cogenerator',
			'well-powered',
			'well-copowered',
			'balanced',
			'products',
			'wide pushouts',
			'coequalizers',
			'cartesian closed',
		],
		non_properties: [
			'essentially small',
			'binary coproducts',
			'strict terminal object',
			'filtered limits',
		],
		monomorphisms: 'injective maps',
		epimorphisms: 'surjective maps',
	},
	{
		id: 'B',
		name: 'category of finite sets and bijections',
		notation: '$\\mathbb{B}$',
		nlab_link: 'https://ncatlab.org/nlab/show/permutation+groupoid',
		objects: 'finite sets',
		morphisms: 'bijective maps',
		description:
			'This category is also known as the permutation groupoid. It appears in the definition of a combinatorial species.',
		related: ['FI', 'FS'],
		tags: ['basic', 'set theory', 'combinatorics', 'badly-behaved'],
		properties: ['locally small', 'essentially small', 'groupoid', 'inhabited'],
		non_properties: ['small', 'connected', 'generator'],
		monomorphisms: 'every morphism',
		epimorphisms: 'every morphism',
	},
	{
		id: 'FI',
		name: 'category of finite sets and injections',
		notation: '$\\mathrm{FI}$',
		objects: 'finite sets',
		morphisms: 'injective maps',
		description:
			'This category is badly-behaved in itself, but plays an important role in representation theory.',
		related: ['B', 'FS'],
		tags: ['basic', 'set theory', 'representation theory', 'badly-behaved'],
		properties: [
			'locally small',
			'initial object',
			'left cancellative',
			'essentially small',
			'generator',
			'connected limits',
			'balanced',
		],
		non_properties: [
			'binary coproducts',
			'small',
			'cogenerator',
			'binary products',
			'filtered colimits',
		],
		monomorphisms: 'every morphism',
		epimorphisms: 'bijective maps',
	},
	{
		id: 'FS',
		name: 'category of finite sets and surjections',
		notation: '$\\mathrm{FS}$',
		objects: 'finite sets',
		morphisms: 'surjective maps',
		description:
			'This category is badly-behaved in itself, but it appears in representation theory. It has two connected components, consisting of the empty set and the non-empty finite sets.',
		related: ['B', 'FI'],
		tags: ['basic', 'set theory', 'representation theory', 'badly-behaved'],
		properties: [
			'locally small',
			'essentially small',
			'right cancellative',
			'balanced',
			'cogenerator',
			'wide pushouts',
			'coequalizers',
		],
		non_properties: [
			'small',
			'connected',
			'generator',
			'filtered limits',
			'pullbacks',
		],
		monomorphisms: 'bijective maps',
		epimorphisms: 'every morphism',
	},
	{
		id: 'On+',
		name: 'delooping of the additive monoid of ordinal numbers',
		notation: '$B(\\mathbf{On},+)$',
		objects: 'a single object',
		morphisms: 'ordinal numbers, with addition as composition',
		description:
			'Every monoid $M$ induces a one-object category $BM$. This also works when $M$ is large, in which case $BM$ is not locally small. In this example, we apply this construction to the large monoid of ordinal numbers with respect to addition.',
		related: ['BN'],
		tags: ['intermediate', 'set theory', 'badly-behaved', 'artificial'],
		properties: [
			'connected',
			'generator',
			'cogenerator',
			'left cancellative',
			'well-copowered',
			'equalizers',
		],
		non_properties: [
			'locally small',
			'initial object',
			'terminal object',
			'right cancellative',
			'zero morphisms',
			'balanced',
			'binary products',
			'binary coproducts',
			'well-powered',
		],
		monomorphisms: 'every ordinal number',
		epimorphisms: 'finite ordinal numbers',
	},
	{
		id: 'FinOrd',
		name: 'category of finite orders',
		notation: '$\\mathbf{FinOrd}$',
		nlab_link: 'https://ncatlab.org/nlab/show/augmented+simplex+category',
		objects: 'finite totally ordered sets',
		morphisms: 'order-preserving maps',
		description:
			'This is also known as the augmented simplex category. The finite orders of the form $\\{0,1,\\dotsc,n-1\\}$ for $n \\in \\mathbb{N}$ provide a skeleton (for $n = 0$ this includes the empty set), and the category is often presented in this way.',
		related: ['Pos', 'FinSet'],
		tags: ['basic', 'topology', 'order theory', 'badly-behaved'],
		properties: [
			'essentially small',
			'locally small',
			'finitely complete',
			'generator',
			'cogenerator',
			'strict initial object',
			'balanced',
			'coequalizers',
		],
		non_properties: [
			'small',
			'binary coproducts',
			'strict terminal object',
			'subobject classifier',
			'cartesian closed',
			'filtered colimits',
		],
		monomorphisms: 'injective order-preserving maps',
		epimorphisms: 'surjective order-preserving maps',
	},
]
