import type { Category } from '$lib/types'

export const categories: Category[] = [
	{
		id: 'Set',
		name: 'The category of sets',
		notation: '\\mathbf{Set}',
		objects: 'sets',
		morphisms: 'functions / maps',
		description:
			'The category of sets plays a fundamental role in category theory. Due to the Yoneda embedding, many results about general categories can be reduced to the category of sets. It is also usually the first example of a category that one encounters.',
		nlab_link: 'https://ncatlab.org/nlab/show/Set',
		properties: ['Grothendieck topos', 'algebraic', 'cogenerator'],
		non_properties: ['preadditive', 'pointed', 'strict terminal object', 'thin'],
		related: ['FinSet'],
	},
	{
		id: 'Ab',
		name: 'The category of abelian groups',
		notation: '\\mathbf{Ab}',
		objects: 'abelian groups',
		morphisms: 'group homomorphisms',
		description: 'This is the prototype of an abelian category.',
		nlab_link: 'https://ncatlab.org/nlab/show/Ab',
		properties: ['abelian', 'algebraic', 'cogenerator'],
		non_properties: ['self-dual', 'thin', 'subobject classifier'],
		related: ['Grp', 'R-Mod'],
	},
	{
		id: 'Top',
		name: 'The category of topological spaces',
		notation: '\\mathbf{Top}',
		objects: 'topological spaces',
		morphisms: 'continuous functions',
		description: 'This is the most basic category of geometric objects.',
		nlab_link: 'https://ncatlab.org/nlab/show/Top',
		properties: [
			'locally small',
			'complete',
			'cocomplete',
			'well-powered',
			'well-copowered',
			'infinitary distributive',
			'generator',
		],
		non_properties: [
			'cartesian closed',
			'locally presentable',
			'pointed',
			'preadditive',
			'strict terminal object',
			'thin',
			'subobject classifier',
			'balanced',
			'cogenerator',
		],
	},
	{
		id: 'Grp',
		name: 'The category of groups',
		notation: '\\mathbf{Grp}',
		objects: 'groups',
		morphisms: 'group homomorphisms',
		nlab_link: 'https://ncatlab.org/nlab/show/Grp',
		properties: ['pointed', 'algebraic', 'balanced'],
		non_properties: [
			'preadditive',
			'self-dual',
			'thin',
			'subobject classifier',
			'cogenerator',
		],
		related: ['Ab', 'Mon'],
	},
	{
		id: 'Ring',
		name: 'The category of rings',
		notation: '\\mathbf{Ring}',
		objects: 'rings',
		morphisms: 'ring homomorphisms',
		nlab_link: 'https://ncatlab.org/nlab/show/Ring',
		description: 'Here, rings always have a unit, and homomorphisms preserve them.',
		properties: ['algebraic', 'strict terminal object'],
		non_properties: [
			'cartesian closed',
			'pointed',
			'strict initial object',
			'thin',
			'subobject classifier',
			'balanced',
			'cogenerator',
		],
		related: ['CRing', 'Rng'],
	},
	{
		id: 'CRing',
		name: 'The category of commutative rings',
		notation: '\\mathbf{CRing}',
		objects: 'commutative rings',
		morphisms: 'ring homomorphisms',
		nlab_link: 'https://ncatlab.org/nlab/show/CRing',
		properties: ['algebraic', 'strict terminal object'],
		non_properties: [
			'cartesian closed',
			'pointed',
			'thin',
			'groupoid',
			'strict initial object',
			'subobject classifier',
			'balanced',
			'cogenerator',
		],
		related: ['Ring', 'Rng'],
	},
	{
		id: 'Rng',
		name: 'The category of rngs',
		notation: '\\mathbf{Rng}',
		objects: 'rngs, that is, non-unital rings',
		morphisms: 'maps that preserve addition and multiplication',
		nlab_link: 'https://ncatlab.org/nlab/show/Rng',
		properties: ['algebraic', 'pointed'],
		non_properties: [
			'thin',
			'groupoid',
			'preadditive',
			'self-dual',
			'subobject classifier',
			'balanced',
			'cogenerator',
		],
		related: ['Ring', 'CRing'],
	},
	{
		id: 'FinSet',
		name: 'The category of finite sets',
		notation: '\\mathbf{FinSet}',
		objects: 'finite sets',
		morphisms: 'functions / maps',
		nlab_link: 'https://ncatlab.org/nlab/show/FinSet',
		properties: [
			'essentially small',
			'locally small',
			'elementary topos',
			'generator',
			'cogenerator',
		],
		non_properties: [
			'small',
			'preadditive',
			'pointed',
			'strict terminal object',
			'thin',
		],
		related: ['Set'],
	},
	{
		id: 'FinAb',
		name: 'The category of finite abelian groups',
		notation: '\\mathbf{FinAb}',
		objects: 'finite abelian groups',
		morphisms: 'group homomorphisms',
		nlab_link: 'https://ncatlab.org/nlab/show/finite+abelian+group',
		properties: [
			'essentially small',
			'abelian',
			'well-powered',
			'well-copowered',
			'self-dual',
		],
		non_properties: [
			'small',
			'complete',
			'groupoid',
			'thin',
			'subobject classifier',
			'generator',
		],
		related: ['Ab'],
	},
	{
		id: 'Set*',
		name: 'The category of pointed sets',
		notation: '\\mathbf{Set}_*',
		objects: 'pointed sets',
		morphisms: 'pointed functions',
		description:
			'This is the category of sets with a distinguished element, often called the base point. A map is called pointed when it preserves the base point.',
		nlab_link: 'https://ncatlab.org/nlab/show/pointed+set',
		properties: ['pointed', 'algebraic', 'subobject classifier', 'cogenerator'],
		non_properties: ['cartesian closed', 'preadditive', 'self-dual', 'thin'],
	},
	{
		id: 'sSet',
		name: 'The category of simplicial sets',
		notation: '\\mathbf{sSet}',
		objects:
			'simplicial sets, i.e. functors $\\Delta^{\\mathrm{op}} \\to \\mathbf{Set}$',
		morphisms: 'natural transformations',
		nlab_link: 'https://ncatlab.org/nlab/show/SimpSet',
		properties: ['Grothendieck topos', 'locally finitely presentable'],
		non_properties: ['thin', 'strict terminal object'],
	},
	{
		id: 'Mon',
		name: 'The category of monoids',
		notation: '\\mathbf{Mon}',
		objects: 'monoids',
		morphisms: 'monoid homomorphisms',
		nlab_link: 'https://ncatlab.org/nlab/show/category+of+monoids',
		properties: ['pointed', 'algebraic'],
		non_properties: [
			'cartesian closed',
			'preadditive',
			'self-dual',
			'thin',
			'subobject classifier',
			'balanced',
			'cogenerator',
		],
		related: ['Grp'],
	},
	{
		id: 'Pos',
		name: 'The category of posets',
		notation: '\\mathbf{Pos}',
		objects: 'partial orders / posets',
		morphisms: 'order-preserving functions',
		nlab_link: 'https://ncatlab.org/nlab/show/Pos',
		properties: ['locally finitely presentable', 'cartesian closed', 'cogenerator'],
		non_properties: [
			'pointed',
			'preadditive',
			'subobject classifier',
			'strict terminal object',
			'thin',
			'algebraic',
			'balanced',
		],
	},
	{
		id: '0',
		name: 'The empty category',
		notation: '0',
		objects: 'no objects',
		morphisms: 'no morphisms',
		description:
			'This is the category with no objects and no morphisms. It is the initial object in the category of small categories.',
		nlab_link: 'https://ncatlab.org/nlab/show/empty+category',
		properties: [
			'connected limits',
			'preadditive',
			'discrete',
			'binary products',
			'finite',
			'balanced',
		],
		non_properties: ['inhabited'],
	},
	{
		id: '1',
		name: 'The trivial category',
		notation: '\\mathbf{1}',
		objects: 'a single object',
		morphisms: 'only the identity morphism',
		description:
			'This is the simplest category, consisting of a single object and only the identity morphism. It is the terminal object in the category of small categories.',
		nlab_link: 'https://ncatlab.org/nlab/show/terminal+category',
		properties: ['trivial', 'finite', 'discrete'],
		non_properties: [],
	},
	{
		id: 'I',
		name: 'The interval category',
		notation: 'I',
		objects: '0,1',
		morphisms: 'a single morphism from 0 to 1',
		description:
			'This is the category with two objects and a single non-identity morphism between them. It has the property that functors out of this category are the same as morphisms.',
		nlab_link: 'https://ncatlab.org/nlab/show/interval+category',
		properties: ['algebraic', 'self-dual', 'thin', 'finite', 'cartesian closed'],
		non_properties: ['pointed', 'groupoid', 'subobject classifier'],
	},
	{
		id: 'M-Set',
		name: 'The category of $M$-sets',
		notation: 'M{-}\\mathbf{Set}',
		objects: 'sets with a left action of a monoid $M$',
		morphisms:
			'maps that are compatible with the $M$-action, meaning $f(m \\cdot x)=m \\cdot f(x)$',
		description:
			'Here, $M$ can be any monoid. But the most important special case is that of a group.',
		nlab_link: 'https://ncatlab.org/nlab/show/MSet',
		properties: ['Grothendieck topos', 'algebraic'],
		non_properties: ['pointed', 'thin', 'strict terminal object'],
	},
	{
		id: 'R-Mod',
		name: 'The category of left $R$-modules',
		notation: 'R{-}\\mathbf{Mod}',
		objects: 'left $R$-modules',
		morphisms: '$R$-linear maps',
		description:
			'This is the category of left modules over a ring $R$. It is the prototype of an abelian category. The category of right modules is the same with the opposite ring $R^{\\mathrm{op}}$, hence not listed here. The non-properties refer to the case that the ring is non-trivial, since for the trivial ring we get a trivial category which has all properties anyway.',
		nlab_link: 'https://ncatlab.org/nlab/show/module',
		properties: ['abelian', 'algebraic', 'cogenerator'],
		non_properties: ['self-dual', 'thin', 'subobject classifier'],
		related: ['Ab'],
	},
	{
		id: 'Met',
		name: 'The category of metric spaces',
		notation: '\\mathbf{Met}',
		objects: 'metric spaces',
		morphisms:
			'non-expansive maps $f$, meaning $d(f(x),f(y)) \\leq d(x,y)$ for all $x,y$',
		nlab_link: 'https://ncatlab.org/nlab/show/Met',
		properties: [
			'locally small',
			'well-powered',
			'well-copowered',
			'equalizers',
			'finite products',
			'initial object',
			'coequalizers',
			'filtered colimits',
			'pushouts',
			'strict initial object',
			'generator',
		],
		non_properties: [
			'essentially small',
			'products',
			'finite coproducts',
			'strict terminal object',
			'pointed',
			'thin',
			'balanced',
			'cartesian closed',
		],
		related: ['Met_oo'],
	},
	{
		id: 'Met_oo',
		name: 'A complete category of metric spaces',
		notation: '\\mathbf{Met}_{\\infty}',
		objects:
			'metric spaces, where the metric is allowed to assume the value $\\infty$',
		morphisms:
			'non-expansive maps $f$, meaning $d(f(x),f(y)) \\leq d(x,y)$ for all $x,y$',
		nlab_link: 'https://ncatlab.org/nlab/show/Met',
		description:
			'The fact that we allow $\\infty$ means that universal constructions work much better.',
		properties: [
			'locally small',
			'well-powered',
			'well-copowered',
			'complete',
			'cocomplete',
			'infinitary distributive',
			'generator',
		],
		non_properties: [
			'essentially small',
			'strict terminal object',
			'pointed',
			'thin',
			'balanced',
			'algebraic',
			'cartesian closed',
		],
		related: ['Met'],
	},
	{
		id: 'Man',
		name: 'The category of smooth manifolds',
		notation: '\\mathbf{Man}',
		objects: 'smooth manifolds',
		morphisms: 'smooth maps',
		nlab_link: 'https://ncatlab.org/nlab/show/Diff',
		description:
			'Here, a smooth manifold is assumed to be finite-dimensional, Hausdorff, and second-countable.',
		properties: [
			'locally small',
			'well-powered',
			'well-copowered',
			'distributive',
			'generator',
		],
		non_properties: [
			'essentially small',
			'products',
			'coproducts',
			'cartesian closed',
			'coequalizers',
			'equalizers',
			'pointed',
			'thin',
			'strict terminal object',
			'balanced',
		],
	},
	{
		id: 'Meas',
		name: 'The category of measurable spaces',
		notation: '\\mathbf{Meas}',
		objects: 'measurable spaces',
		morphisms: 'measurable maps',
		nlab_link: 'https://ncatlab.org/nlab/show/Meas',
		description:
			'Limits and colimits can be constructed in the same way as for topological spaces.',
		properties: [
			'locally small',
			'well-powered',
			'well-copowered',
			'complete',
			'cocomplete',
			'infinitary distributive',
			'generator',
			'cogenerator',
		],
		non_properties: [
			'pointed',
			'thin',
			'cartesian closed',
			'strict terminal object',
			'balanced',
		],
	},
	{
		id: 'N',
		name: 'The partial order of natural numbers',
		notation: '(\\mathbb{N},\\leq)',
		objects: 'natural numbers $0, 1, 2, \\dotsc$',
		morphisms: 'a unique morphism $n \\to m$ if $n \\leq m$',
		description:
			'This can also be seen as the path category of the infinite linear graph $\\bullet \\to \\bullet \\to \\bullet \\to \\cdots$.',
		properties: [
			'small',
			'finitely cocomplete',
			'binary products',
			'thin',
			'connected limits',
		],
		non_properties: ['cocomplete', 'terminal object', 'cartesian closed', 'finite'],
		related: ['On'],
	},
	{
		id: 'Cat',
		name: 'The category of small categories',
		notation: '\\mathbf{Cat}',
		objects: 'small categories',
		morphisms: 'functors',
		description:
			'This is the category of small categories and functors between them. It is the prototype of a 2-category, but here we only treat it as a 1-category.',
		nlab_link: 'https://ncatlab.org/nlab/show/Cat',
		properties: ['cartesian closed', 'locally finitely presentable'],
		non_properties: [
			'pointed',
			'thin',
			'strict terminal object',
			'subobject classifier',
			'algebraic',
			'balanced',
			'cogenerator',
		],
	},
	{
		id: 'On',
		name: 'The partial order of ordinal numbers',
		notation: '(\\mathbf{On},\\leq)',
		objects: 'ordinal numbers',
		morphisms: 'a unique morphism $\\alpha \\to \\beta$ if $\\alpha \\leq \\beta$',
		description: 'This is a large variant of the partial order of natural numbers.',
		properties: [
			'thin',
			'locally small',
			'cocomplete',
			'binary products',
			'connected limits',
			'well-powered',
		],
		non_properties: ['essentially small', 'terminal object', 'well-copowered'],
		related: ['N'],
	},
	{
		id: 'LRS',
		name: 'The category of locally ringed spaces',
		notation: '\\mathbf{LRS}',
		objects: 'locally ringed spaces',
		morphisms: 'morphism of locally ringed spaces',
		properties: [
			'locally small',
			'complete',
			'cocomplete',
			'well-powered',
			'well-copowered',
			'infinitary distributive',
		],
		non_properties: ['pointed', 'thin', 'cartesian closed', 'strict terminal object'],
		related: ['Sch'],
	},
	{
		id: 'Sch',
		name: 'The category of schemes',
		notation: '\\mathbf{Sch}',
		objects: 'schemes',
		morphisms: 'morphism of schemes',
		properties: [
			'locally small',
			'finitely complete',
			'well-powered',
			'infinitary distributive',
		],
		non_properties: [
			'pointed',
			'thin',
			'essentially small',
			'coequalizers',
			'products',
			'cartesian closed',
			'strict terminal object',
		],
		related: ['LRS'],
	},
	{
		id: 'Fld',
		name: 'The category of fields',
		notation: '\\mathbf{Fld}',
		objects: 'fields',
		morphisms: 'field homomorphisms (i.e., ring homomorphisms)',
		description: 'This is a typical example of a bad category of good objects.',
		nlab_link: 'https://ncatlab.org/nlab/show/Field',
		properties: [
			'locally small',
			'equalizers',
			'pullbacks',
			'filtered colimits',
			'connected limits',
			'inhabited',
		],
		non_properties: [
			'initial object',
			'terminal object',
			'connected',
			'essentially small',
			'preadditive',
			'well-powered',
			'well-copowered',
			'coequalizers',
			'pushouts',
			'balanced',
			'generator',
			'cogenerator',
		],
	},
	{
		id: 'FreeAb',
		name: 'The category of free abelian groups',
		notation: '\\mathbf{FreeAb}',
		objects: 'free abelian groups',
		morphisms: 'group homomorphisms',
		properties: [
			'additive',
			'coproducts',
			'well-powered',
			'well-copowered',
			'equalizers',
			'generator',
			'cogenerator',
		],
		non_properties: [
			'essentially small',
			'products',
			'subobject classifier',
			'coequalizers',
			'balanced',
			'filtered colimits',
		],
		related: ['Ab'],
	},
]
