import type { Category } from '$lib/types'

export const categories: Category[] = [
	{
		id: 'Set',
		name: 'The category of sets',
		notation: '$\\mathbf{Set}$',
		objects: 'sets',
		morphisms: 'maps',
		description:
			'The category of sets plays a fundamental role in category theory. Due to the Yoneda embedding, many results about general categories can be reduced to the category of sets. It is also usually the first example of a category that one encounters.',
		nlab_link: 'https://ncatlab.org/nlab/show/Set',
		properties: ['Grothendieck topos', 'finitary algebraic'],
		non_properties: ['zero morphisms', 'strict terminal object', 'thin'],
		related: ['FinSet'],
	},
	{
		id: 'Ab',
		name: 'The category of abelian groups',
		notation: '$\\mathbf{Ab}$',
		objects: 'abelian groups',
		morphisms: 'group homomorphisms',
		description: 'This is the prototype of an abelian category.',
		nlab_link: 'https://ncatlab.org/nlab/show/Ab',
		properties: ['abelian', 'finitary algebraic'],
		non_properties: ['self-dual', 'thin', 'subobject classifier'],
		related: ['Grp', 'R-Mod'],
	},
	{
		id: 'Top',
		name: 'The category of topological spaces',
		notation: '$\\mathbf{Top}$',
		objects: 'topological spaces',
		morphisms: 'continuous functions',
		description: 'This is the most basic category of geometric objects.',
		nlab_link: 'https://ncatlab.org/nlab/show/Top',
		properties: [
			'locally small',
			'complete',
			'cocomplete',
			'well-powered',
			'well-copowered',
			'infinitary distributive',
			'generator',
			'disjoint coproducts',
		],
		non_properties: [
			'cartesian closed',
			'locally presentable',
			'zero morphisms',
			'strict terminal object',
			'thin',
			'subobject classifier',
			'balanced',
			'cogenerator',
			'filtered colimits that commute with finite limits',
		],
	},
	{
		id: 'Grp',
		name: 'The category of groups',
		notation: '$\\mathbf{Grp}$',
		objects: 'groups',
		morphisms: 'group homomorphisms',
		nlab_link: 'https://ncatlab.org/nlab/show/Grp',
		properties: ['pointed', 'finitary algebraic', 'balanced', 'disjoint coproducts'],
		non_properties: [
			'preadditive',
			'self-dual',
			'thin',
			'subobject classifier',
			'cogenerator',
		],
		related: ['Ab', 'Mon'],
	},
	{
		id: 'Ring',
		name: 'The category of rings',
		notation: '$\\mathbf{Ring}$',
		objects: 'rings',
		morphisms: 'ring homomorphisms',
		nlab_link: 'https://ncatlab.org/nlab/show/Ring',
		description: 'Here, rings always have a unit, and homomorphisms preserve them.',
		properties: ['finitary algebraic', 'strict terminal object'],
		non_properties: [
			'cartesian closed',
			'pointed',
			'strict initial object',
			'thin',
			'subobject classifier',
			'balanced',
			'cogenerator',
			'disjoint finite coproducts',
		],
		related: ['CRing', 'Rng'],
	},
	{
		id: 'CRing',
		name: 'The category of commutative rings',
		notation: '$\\mathbf{CRing}$',
		objects: 'commutative rings',
		morphisms: 'ring homomorphisms',
		nlab_link: 'https://ncatlab.org/nlab/show/CRing',
		properties: ['finitary algebraic', 'strict terminal object'],
		non_properties: [
			'cartesian closed',
			'pointed',
			'thin',
			'groupoid',
			'strict initial object',
			'subobject classifier',
			'balanced',
			'cogenerator',
			'disjoint finite coproducts',
		],
		related: ['Ring', 'Rng'],
	},
	{
		id: 'Rng',
		name: 'The category of rngs',
		notation: '$\\mathbf{Rng}$',
		objects: 'rngs, that is, non-unital rings',
		morphisms: 'maps that preserve addition and multiplication',
		nlab_link: 'https://ncatlab.org/nlab/show/Rng',
		properties: ['finitary algebraic', 'pointed', 'disjoint coproducts'],
		non_properties: [
			'thin',
			'groupoid',
			'preadditive',
			'self-dual',
			'subobject classifier',
			'balanced',
			'cogenerator',
		],
		related: ['Ring', 'CRing'],
	},
	{
		id: 'FinSet',
		name: 'The category of finite sets',
		notation: '$\\mathbf{FinSet}$',
		objects: 'finite sets',
		morphisms: 'functions / maps',
		nlab_link: 'https://ncatlab.org/nlab/show/FinSet',
		properties: [
			'essentially small',
			'locally small',
			'elementary topos',
			'generator',
			'cogenerator',
		],
		non_properties: ['small', 'zero morphisms', 'strict terminal object', 'thin'],
		related: ['Set'],
	},
	{
		id: 'FinAb',
		name: 'The category of finite abelian groups',
		notation: '$\\mathbf{FinAb}$',
		objects: 'finite abelian groups',
		morphisms: 'group homomorphisms',
		nlab_link: 'https://ncatlab.org/nlab/show/finite+abelian+group',
		properties: ['essentially small', 'abelian', 'self-dual'],
		non_properties: [
			'small',
			'complete',
			'groupoid',
			'thin',
			'subobject classifier',
			'generator',
		],
		related: ['Ab'],
	},
	{
		id: 'Set*',
		name: 'The category of pointed sets',
		notation: '$\\mathbf{Set}_*$',
		objects: 'pointed sets',
		morphisms: 'pointed functions',
		description:
			'This is the category of sets with a distinguished element, often called the base point. A map is called pointed when it preserves the base point.',
		nlab_link: 'https://ncatlab.org/nlab/show/pointed+set',
		properties: [
			'pointed',
			'finitary algebraic',
			'subobject classifier',
			'cogenerator',
			'disjoint coproducts',
		],
		non_properties: ['cartesian closed', 'preadditive', 'self-dual', 'thin'],
	},
	{
		id: 'sSet',
		name: 'The category of simplicial sets',
		notation: '$\\mathbf{sSet}$',
		objects:
			'simplicial sets, i.e. functors $\\Delta^{\\mathrm{op}} \\to \\mathbf{Set}$',
		morphisms: 'natural transformations',
		nlab_link: 'https://ncatlab.org/nlab/show/SimpSet',
		properties: ['Grothendieck topos', 'locally finitely presentable'],
		non_properties: ['thin', 'strict terminal object'],
	},
	{
		id: 'Mon',
		name: 'The category of monoids',
		notation: '$\\mathbf{Mon}$',
		objects: 'monoids',
		morphisms: 'monoid homomorphisms',
		nlab_link: 'https://ncatlab.org/nlab/show/category+of+monoids',
		properties: ['pointed', 'finitary algebraic', 'disjoint coproducts'],
		non_properties: [
			'cartesian closed',
			'preadditive',
			'self-dual',
			'thin',
			'subobject classifier',
			'balanced',
			'cogenerator',
		],
		related: ['Grp'],
	},
	{
		id: 'Pos',
		name: 'The category of posets',
		notation: '$\\mathbf{Pos}$',
		objects: 'partial orders / posets',
		morphisms: 'order-preserving functions',
		nlab_link: 'https://ncatlab.org/nlab/show/Pos',
		properties: [
			'locally finitely presentable',
			'cartesian closed',
			'cogenerator',
			'disjoint coproducts',
		],
		non_properties: [
			'zero morphisms',
			'subobject classifier',
			'strict terminal object',
			'thin',
			'finitary algebraic',
			'balanced',
		],
	},
	{
		id: '0',
		name: 'The empty category',
		notation: '$0$',
		objects: 'no objects',
		morphisms: 'no morphisms',
		description:
			'This is the category with no objects and no morphisms. It is the initial object in the category of small categories.',
		nlab_link: 'https://ncatlab.org/nlab/show/empty+category',
		properties: ['preadditive', 'discrete', 'binary products', 'finite'],
		non_properties: ['inhabited'],
	},
	{
		id: '1',
		name: 'The trivial category',
		notation: '$\\mathbf{1}$',
		objects: 'a single object',
		morphisms: 'only the identity morphism',
		description:
			'This is the simplest category, consisting of a single object and only the identity morphism. It is the terminal object in the category of small categories.',
		nlab_link: 'https://ncatlab.org/nlab/show/terminal+category',
		properties: ['trivial', 'finite', 'discrete'],
		non_properties: [],
		related: ['2'],
	},
	{
		id: '2',
		name: 'The discrete category on two objects',
		notation: '$\\mathbf{2}$',
		objects: 'two objects',
		morphisms: 'only the identity morphisms',
		description:
			'For a more concrete representation, this is the subcategory of $\\mathbf{CRing}$ of the two fields $\\mathbb{F}_2$ and $\\mathbb{F}_3$.',
		properties: ['discrete', 'finite', 'inhabited'],
		non_properties: ['connected'],
		related: ['1'],
	},
	{
		id: 'I',
		name: 'The interval category',
		notation: '$I$',
		objects: '0,1',
		morphisms: 'a single morphism from 0 to 1',
		description:
			'This is the category with two objects and a single non-identity morphism between them. It has the property that functors out of this category are the same as morphisms.',
		nlab_link: 'https://ncatlab.org/nlab/show/interval+category',
		properties: ['finitary algebraic', 'self-dual', 'finite', 'cartesian closed'],
		non_properties: ['pointed', 'groupoid', 'subobject classifier'],
	},
	{
		id: 'M-Set',
		name: 'The category of M-sets',
		notation: '$M{-}\\mathbf{Set}$',
		objects: 'sets with a left action of a monoid $M$',
		morphisms:
			'maps that are compatible with the $M$-action, meaning $f(m \\cdot x)=m \\cdot f(x)$',
		description:
			'Here, $M$ can be any monoid. But the most important special case is that of a group.',
		nlab_link: 'https://ncatlab.org/nlab/show/MSet',
		properties: ['Grothendieck topos', 'finitary algebraic'],
		non_properties: ['pointed', 'thin', 'strict terminal object'],
	},
	{
		id: 'R-Mod',
		name: 'The category of left R-modules',
		notation: '$R{-}\\mathbf{Mod}$',
		objects: 'left $R$-modules',
		morphisms: '$R$-linear maps',
		description:
			'This is the category of left modules over a ring $R$. It is the prototype of an abelian category. The category of right modules is the same with the opposite ring $R^{\\mathrm{op}}$, hence not listed here. The non-properties refer to the case that the ring is non-trivial, since for the trivial ring we get a trivial category which has all properties anyway.',
		nlab_link: 'https://ncatlab.org/nlab/show/module',
		properties: ['abelian', 'finitary algebraic'],
		non_properties: ['self-dual', 'thin', 'subobject classifier'],
		related: ['Ab'],
	},
	{
		id: 'Met',
		name: 'The category of metric spaces',
		notation: '$\\mathbf{Met}$',
		objects: 'metric spaces',
		morphisms:
			'non-expansive maps $f$, meaning $d(f(x),f(y)) \\leq d(x,y)$ for all $x,y$',
		nlab_link: 'https://ncatlab.org/nlab/show/Met',
		properties: [
			'locally small',
			'well-powered',
			'well-copowered',
			'equalizers',
			'finite products',
			'coequalizers',
			'filtered colimits',
			'strict initial object',
			'generator',
			'cogenerator',
		],
		non_properties: [
			'essentially small',
			'products',
			'finite coproducts',
			'strict terminal object',
			'pointed',
			'thin',
			'balanced',
			'cartesian closed',
		],
		related: ['Met_oo'],
	},
	{
		id: 'Met_oo',
		name: 'A complete category of metric spaces',
		notation: '$\\mathbf{Met}_{\\infty}$',
		objects:
			'metric spaces, where the metric is allowed to assume the value $\\infty$',
		morphisms:
			'non-expansive maps $f$, meaning $d(f(x),f(y)) \\leq d(x,y)$ for all $x,y$',
		nlab_link: 'https://ncatlab.org/nlab/show/Met',
		description:
			'The fact that we allow $\\infty$ means that universal constructions work much better.',
		properties: [
			'locally small',
			'well-powered',
			'well-copowered',
			'complete',
			'cocomplete',
			'infinitary distributive',
			'generator',
			'cogenerator',
			'disjoint coproducts',
		],
		non_properties: [
			'essentially small',
			'strict terminal object',
			'pointed',
			'thin',
			'balanced',
			'finitary algebraic',
			'cartesian closed',
		],
		related: ['Met'],
	},
	{
		id: 'Man',
		name: 'The category of smooth manifolds',
		notation: '$\\mathbf{Man}$',
		objects: 'smooth manifolds',
		morphisms: 'smooth maps',
		nlab_link: 'https://ncatlab.org/nlab/show/Diff',
		description:
			'Here, a smooth manifold is assumed to be finite-dimensional, Hausdorff, and second-countable.',
		properties: [
			'locally small',
			'well-powered',
			'well-copowered',
			'distributive',
			'generator',
			'disjoint finite coproducts',
		],
		non_properties: [
			'essentially small',
			'products',
			'coproducts',
			'cartesian closed',
			'coequalizers',
			'equalizers',
			'pointed',
			'thin',
			'strict terminal object',
			'balanced',
		],
	},
	{
		id: 'Meas',
		name: 'The category of measurable spaces',
		notation: '$\\mathbf{Meas}$',
		objects: 'measurable spaces',
		morphisms: 'measurable maps',
		nlab_link: 'https://ncatlab.org/nlab/show/Meas',
		description:
			'Limits and colimits can be constructed in the same way as for topological spaces.',
		properties: [
			'locally small',
			'well-powered',
			'well-copowered',
			'complete',
			'cocomplete',
			'infinitary distributive',
			'generator',
			'cogenerator',
			'disjoint coproducts',
		],
		non_properties: [
			'pointed',
			'thin',
			'cartesian closed',
			'strict terminal object',
			'balanced',
		],
	},
	{
		id: 'N',
		name: 'The partial order of natural numbers',
		notation: '$(\\mathbb{N},\\leq)$',
		objects: 'natural numbers $0, 1, 2, \\dotsc$',
		morphisms: 'a unique morphism $n \\to m$ if $n \\leq m$',
		description:
			'This can also be seen as the path category of the infinite linear graph $\\bullet \\to \\bullet \\to \\bullet \\to \\cdots$.',
		properties: [
			'small',
			'finitely cocomplete',
			'binary products',
			'thin',
			'connected limits',
		],
		non_properties: ['cocomplete', 'terminal object', 'cartesian closed', 'finite'],
		related: ['On'],
	},
	{
		id: 'Cat',
		name: 'The category of small categories',
		notation: '$\\mathbf{Cat}$',
		objects: 'small categories',
		morphisms: 'functors',
		description:
			'This is the category of small categories and functors between them. It is the prototype of a 2-category, but here we only treat it as a 1-category.',
		nlab_link: 'https://ncatlab.org/nlab/show/Cat',
		properties: [
			'cartesian closed',
			'locally finitely presentable',
			'disjoint coproducts',
		],
		non_properties: [
			'pointed',
			'thin',
			'strict terminal object',
			'subobject classifier',
			'finitary algebraic',
			'balanced',
			'cogenerator',
		],
	},
	{
		id: 'On',
		name: 'The partial order of ordinal numbers',
		notation: '$(\\mathbf{On},\\leq)$',
		objects: 'ordinal numbers',
		morphisms: 'a unique morphism $\\alpha \\to \\beta$ if $\\alpha \\leq \\beta$',
		description: 'This is a large variant of the partial order of natural numbers.',
		properties: [
			'thin',
			'locally small',
			'cocomplete',
			'binary products',
			'connected limits',
			'well-powered',
		],
		non_properties: ['essentially small', 'terminal object', 'well-copowered'],
		related: ['N'],
	},
	{
		id: 'LRS',
		name: 'The category of locally ringed spaces',
		notation: '$\\mathbf{LRS}$',
		objects: 'locally ringed spaces',
		morphisms: 'morphism of locally ringed spaces',
		properties: [
			'locally small',
			'complete',
			'cocomplete',
			'well-powered',
			'well-copowered',
			'infinitary distributive',
			'disjoint coproducts',
		],
		non_properties: ['pointed', 'thin', 'cartesian closed', 'strict terminal object'],
		related: ['Sch'],
	},
	{
		id: 'Sch',
		name: 'The category of schemes',
		notation: '$\\mathbf{Sch}$',
		objects: 'schemes',
		morphisms: 'morphism of schemes',
		properties: [
			'locally small',
			'finitely complete',
			'well-powered',
			'infinitary distributive',
			'disjoint coproducts',
		],
		non_properties: [
			'pointed',
			'thin',
			'essentially small',
			'coequalizers',
			'products',
			'cartesian closed',
			'strict terminal object',
		],
		related: ['LRS', 'Z'],
	},
	{
		id: 'Fld',
		name: 'The category of fields',
		notation: '$\\mathbf{Fld}$',
		objects: 'fields',
		morphisms: 'field homomorphisms (i.e., ring homomorphisms)',
		description: 'This is a typical example of a bad category of good objects.',
		nlab_link: 'https://ncatlab.org/nlab/show/Field',
		properties: [
			'locally small',
			'filtered colimits',
			'connected limits',
			'inhabited',
			'left cancellative',
		],
		non_properties: [
			'initial object',
			'terminal object',
			'connected',
			'essentially small',
			'preadditive',
			'well-powered',
			'well-copowered',
			'coequalizers',
			'pushouts',
			'balanced',
			'generator',
			'cogenerator',
			'right cancellative',
		],
	},
	{
		id: 'FreeAb',
		name: 'The category of free abelian groups',
		notation: '$\\mathbf{FreeAb}$',
		objects: 'free abelian groups',
		morphisms: 'group homomorphisms',
		properties: [
			'additive',
			'well-powered',
			'well-copowered',
			'equalizers',
			'generator',
			'cogenerator',
			'disjoint coproducts',
		],
		non_properties: [
			'essentially small',
			'products',
			'subobject classifier',
			'coequalizers',
			'balanced',
			'filtered colimits',
		],
		related: ['Ab'],
	},
	{
		id: 'Z',
		name: 'The category of Z-functors',
		notation: '$[\\mathbf{CRing}, \\mathbf{Set}]$',
		objects: 'Z-functors, i.e. functors from commutative rings to sets',
		morphisms: 'natural transformations',
		description:
			'This category is used in functorial algebraic geometry. It also provides a typical example of a functor category that is not locally small, but nevertheless relevant. Most of its properties are directly derived from the category of sets, so other functor categories $[\\mathbf{C}, \\mathbf{Set}]$ for large categories $\\mathbf{C}$ will be similar.',
		properties: [
			'complete',
			'cocomplete',
			'balanced',
			'infinitary distributive',
			'filtered colimits that commute with finite limits',
			'disjoint coproducts',
		],
		non_properties: [
			'locally small',
			'essentially small',
			'groupoid',
			'thin',
			'strict terminal object',
		],
		related: ['Sch', 'Set'],
	},
	{
		id: 'BG',
		name: 'delooping of a group',
		notation: '$BG$',
		objects: 'a single object',
		morphisms: 'the elements of a group $G$',
		nlab_link: 'https://ncatlab.org/nlab/show/delooping',
		description:
			'Every group $G$ yields a groupoid $BG$ with a single object, morphisms given by the elements of $G$, and composition given by the group operation. When $G$ is trivial, then $BG$ is the trivial category. However, in the non-properties below, we refer to the case that $G$ is non-trivial. The non-property "finite" refers to the case that $G$ is "generic" and hence infinite.',
		properties: ['small', 'groupoid', 'connected', 'generator'],
		non_properties: ['trivial', 'finite', 'thin', 'zero morphisms'],
	},
	{
		id: 'BN',
		name: 'delooping of the additive monoid of natural numbers',
		notation: '$B\\mathbb{N}$',
		objects: 'a single object',
		morphisms: 'the natural numbers, with addition serving as composition',
		description:
			'Every monoid $M$ induces a one-object category $BM$ with morphisms given by the elements of $M$, and composition given by the monoid operation. Some of the properties of this category depend on the specific monoid. In this example, we take the commutative monoid $M = (\\mathbb{N},+,0)$.',
		properties: [
			'small',
			'connected',
			'self-dual',
			'generator',
			'pullbacks',
			'left cancellative',
		],
		non_properties: [
			'groupoid',
			'finite',
			'initial object',
			'thin',
			'balanced',
			'zero morphisms',
			'binary products',
			'equalizers',
			'filtered colimits',
		],
		related: ['BG'],
	},
	{
		id: 'walking_pair',
		name: 'The walking parallel pair of morphisms',
		notation: '$\\{0 \\rightrightarrows 1 \\}$',
		objects: 'two objects $0$ and $1$',
		morphisms: 'identities and two parallel morphisms from $0$ to $1$',
		description:
			"This is the 'walking parallel pair' of morphisms. The name comes from the fact that it consists of two parallel morphisms, and a functor out of this category is the same as a parallel pair of morphisms in the target category.",
		related: ['I'],
		nlab_link: 'https://ncatlab.org/nlab/show/walking+structure',
		properties: [
			'finite',
			'self-dual',
			'connected',
			'generator',
			'filtered limits',
			'left cancellative',
		],
		non_properties: [
			'thin',
			'groupoid',
			'initial object',
			'balanced',
			'zero morphisms',
			'binary products',
			'equalizers',
			'pullbacks',
		],
	},
	{
		id: 'walking_isomorphism',
		name: 'The walking isomorphism',
		notation: '$\\{0 \\rightleftarrows 1\\}$',
		objects: 'two objects $0$ and $1$',
		morphisms:
			'identities, and two morphisms $0 \\to 1$ and $1 \\to 0$ that are mutually inverse',
		description:
			"This is the 'walking isomorphism' category. The name comes from the fact that it consists of two objects and an isomorphism between them, and a functor out of this category is the same as an isomorphism in the target category. The walking isomorphism is actually equivalent to the trivial category.",
		nlab_link: 'https://ncatlab.org/nlab/show/walking+isomorphism',
		related: ['I', '1'],
		properties: ['trivial', 'finite'],
		non_properties: ['discrete'],
	},
	{
		id: 'Setne',
		name: 'The category of non-empty sets',
		notation: '$\\mathbf{Set}_{\\neq \\emptyset}$',
		objects: 'non-empty sets',
		morphisms: 'maps',
		description:
			'This entry demonstrates that removing an object (the empty set) can drastically change the properties of a category. In particular, this category is neither complete nor cocomplete.',
		related: ['Set'],
		nlab_link: 'https://ncatlab.org/nlab/show/inhabited+set',
		properties: [
			'locally small',
			'generator',
			'cogenerator',
			'well-powered',
			'well-copowered',
			'balanced',
			'products',
			'connected colimits',
			'cartesian closed',
		],
		non_properties: [
			'initial object',
			'thin',
			'groupoid',
			'essentially small',
			'equalizers',
			'binary coproducts',
			'strict terminal object',
			'filtered limits',
		],
	},
]
