import type { CategoryID } from './categories.data'
import type { PropertyID } from './properties.data'

export const CATEGORY_NON_PROPERTIES: [CategoryID, PropertyID, string][] = [
	['Set', 'strict terminal object', ''],
	['Set', 'skeletal', 'trivial'],
	['Ab', 'split abelian', ''],
	['Ab', 'skeletal', 'trivial'],
	['Top', 'cartesian closed', ''],
	['Top', 'locally presentable', ''],
	['Top', 'strict terminal object', ''],
	['Top', 'balanced', ''],
	['Top', 'cogenerator', ''],
	['Top', 'exact filtered colimits', ''],
	['Top', 'skeletal', 'trivial'],
	['Grp', 'subobject classifier', ''],
	['Grp', 'cogenerator', ''],
	['Grp', 'skeletal', 'trivial'],
	['Vect', 'trivial', ''],
	['Vect', 'skeletal', 'trivial'],
	['Ring', 'strict initial object', ''],
	['Ring', 'balanced', ''],
	['Ring', 'cogenerator', ''],
	['Ring', 'disjoint finite coproducts', ''],
	['Ring', 'skeletal', 'trivial'],
	['CRing', 'strict initial object', ''],
	['CRing', 'balanced', ''],
	['CRing', 'cogenerator', ''],
	['CRing', 'disjoint finite coproducts', ''],
	['CRing', 'skeletal', 'trivial'],
	['Rng', 'preadditive', ''],
	['Rng', 'balanced', ''],
	['Rng', 'cogenerator', ''],
	['Rng', 'skeletal', 'trivial'],
	['FinSet', 'small', ''],
	['FinSet', 'strict terminal object', ''],
	['FinSet', 'sequential limits', ''],
	['FinSet', 'sequential colimits', ''],
	['FinSet', 'skeletal', 'trivial'],
	['FinAb', 'small', ''],
	['FinAb', 'generator', ''],
	['FinAb', 'split abelian', ''],
	['FinAb', 'sequential limits', ''],
	['FinAb', 'skeletal', 'trivial'],
	['Abfg', 'small', ''],
	['Abfg', 'cogenerator', ''],
	['Abfg', 'split abelian', ''],
	['Abfg', 'countable products', ''],
	['Abfg', 'countable coproducts', ''],
	['Abfg', 'skeletal', 'trivial'],
	['Set*', 'preadditive', ''],
	['Set*', 'skeletal', 'trivial'],
	['sSet', 'strict terminal object', ''],
	['sSet', 'skeletal', 'trivial'],
	['Mon', 'preadditive', ''],
	['Mon', 'balanced', ''],
	['Mon', 'cogenerator', ''],
	['Mon', 'skeletal', 'trivial'],
	['Pos', 'strict terminal object', ''],
	['Pos', 'finitary algebraic', ''],
	['Pos', 'balanced', ''],
	['Pos', 'skeletal', 'trivial'],
	['0', 'inhabited', ''],
	['2', 'connected', ''],
	['I', 'subobject classifier', ''],
	['M-Set', 'strict terminal object', ''],
	['M-Set', 'skeletal', 'trivial'],
	['R-Mod', 'split abelian', ''],
	['R-Mod', 'skeletal', 'trivial'],
	['Met', 'sequential limits', ''],
	['Met', 'finite coproducts', ''],
	['Met', 'strict terminal object', ''],
	['Met', 'balanced', ''],
	['Met', 'cartesian closed', ''],
	['Met', 'essentially small', ''],
	['Met', 'exact filtered colimits', '2.7 in https://arxiv.org/abs/2006.01399'],
	['Met', 'skeletal', 'trivial'],
	['Met_oo', 'strict terminal object', ''],
	['Met_oo', 'balanced', ''],
	['Met_oo', 'cartesian closed', ''],
	['Met_oo', 'exact filtered colimits', '2.7 in https://arxiv.org/abs/2006.01399'],
	['Met_oo', 'skeletal', 'trivial'],
	['Met_c', 'products', ''],
	['Met_c', 'strict terminal object', ''],
	['Met_c', 'balanced', ''],
	['Met_c', 'cartesian closed', ''],
	['Met_c', 'skeletal', 'trivial'],
	['Ban', 'preadditive', ''],
	['Ban', 'balanced', ''],
	['Ban', 'exact filtered colimits', ''],
	['Ban', 'skeletal', 'trivial'],
	['Man', 'essentially small', ''],
	['Man', 'countable products', ''],
	['Man', 'coproducts', ''],
	['Man', 'cartesian closed', ''],
	['Man', 'coequalizers', ''],
	['Man', 'equalizers', ''],
	['Man', 'strict terminal object', ''],
	['Man', 'balanced', ''],
	['Man', 'skeletal', 'trivial'],
	['Meas', 'cartesian closed', ''],
	['Meas', 'strict terminal object', ''],
	['Meas', 'balanced', ''],
	['Meas', 'skeletal', 'trivial'],
	['N', 'countable coproducts', ''],
	['N', 'essentially finite', ''],
	['Cat', 'strict terminal object', ''],
	['Cat', 'finitary algebraic', ''],
	['Cat', 'balanced', ''],
	['Cat', 'cogenerator', ''],
	['Cat', 'skeletal', 'trivial'],
	['On', 'terminal object', ''],
	['On', 'well-copowered', ''],
	['LRS', 'cartesian closed', ''],
	['LRS', 'strict terminal object', ''],
	['LRS', 'skeletal', 'trivial'],
	['Sch', 'coequalizers', ''],
	['Sch', 'countable products', ''],
	['Sch', 'cartesian closed', ''],
	['Sch', 'strict terminal object', ''],
	['Sch', 'skeletal', 'trivial'],
	['Fld', 'connected', ''],
	['Fld', 'well-copowered', ''],
	['Fld', 'pushouts', ''],
	['Fld', 'balanced', ''],
	['Fld', 'generator', ''],
	['Fld', 'cogenerator', ''],
	['Fld', 'skeletal', 'trivial'],
	['FreeAb', 'countable products', ''],
	['FreeAb', 'balanced', ''],
	['FreeAb', 'filtered colimits', 'https://math.stackexchange.com/questions/5025660'],
	['FreeAb', 'skeletal', 'trivial'],
	['Z', 'locally essentially small', ''],
	['Z', 'strict terminal object', ''],
	['Z', 'skeletal', 'trivial'],
	['BG', 'zero morphisms', ''],
	['BG', 'essentially finite', ''],
	['BGf', 'zero morphisms', ''],
	['BN', 'essentially finite', ''],
	['BN', 'zero morphisms', ''],
	['BN', 'equalizers', ''],
	['BN', 'sequential limits', ''],
	['walking_pair', 'initial object', ''],
	['walking_pair', 'zero morphisms', ''],
	['walking_pair', 'binary products', ''],
	['walking_pair', 'equalizers', ''],
	['walking_pair', 'pullbacks', ''],
	['walking_isomorphism', 'skeletal', 'The two objects are isomorphic, but different.'],
	['Setne', 'binary coproducts', ''],
	['Setne', 'strict terminal object', ''],
	['Setne', 'sequential limits', ''],
	['Setne', 'skeletal', 'trivial'],
	['B', 'small', ''],
	['B', 'connected', ''],
	['B', 'generator', ''],
	['B', 'essentially finite', ''],
	['B', 'skeletal', 'trivial'],
	['FI', 'binary coproducts', ''],
	['FI', 'small', ''],
	['FI', 'cogenerator', ''],
	['FI', 'binary products', ''],
	['FI', 'sequential colimits', ''],
	['FI', 'essentially finite', ''],
	['FI', 'skeletal', 'trivial'],
	['FS', 'small', ''],
	['FS', 'connected', ''],
	['FS', 'generator', ''],
	['FS', 'sequential limits', ''],
	['FS', 'pullbacks', ''],
	['FS', 'essentially finite', ''],
	['FS', 'skeletal', 'trivial'],
	['On+', 'locally essentially small', ''],
	['On+', 'initial object', ''],
	['On+', 'terminal object', ''],
	['On+', 'right cancellative', ''],
	['On+', 'zero morphisms', ''],
	['On+', 'balanced', ''],
	['On+', 'binary products', ''],
	['On+', 'binary coproducts', ''],
	['On+', 'well-powered', ''],
	['FinOrd', 'small', ''],
	['FinOrd', 'binary coproducts', ''],
	['FinOrd', 'strict terminal object', ''],
	['FinOrd', 'subobject classifier', ''],
	['FinOrd', 'cartesian closed', ''],
	['FinOrd', 'sequential colimits', ''],
	['FinOrd', 'countable products', ''],
	['FinOrd', 'skeletal', 'trivial'],
	['Rel', 'preadditive', ''],
	['Rel', 'Cauchy complete', ''],
	['Rel', 'skeletal', 'trivial'],
	['Sp', 'locally small', ''],
	['Sp', 'strict terminal object', ''],
	['Sp', 'countable products', ''],
	['Sp', 'countable coproducts', ''],
	['Sp', 'skeletal', 'trivial'],
	['real_interval', 'essentially finite', ''],
	['real_interval', 'locally finitely presentable', ''],
]
