import type { CategoryID } from './categories.data'
import type { NonEmptyArray } from '$lib/commons/utils'

export const CATEGORY_RELATIONS: Partial<Record<CategoryID, NonEmptyArray<CategoryID>>> =
	{
		'1': ['2'],
		'2': ['1'],
		'Ab': ['Grp', 'R-Mod'],
		'Abfg': ['Ab', 'FinAb'],
		'B': ['FI', 'FS'],
		'Ban': ['Met'],
		'BG': ['BGf', 'BN'],
		'BGf': ['BG'],
		'BN': ['BG', 'On+'],
		'CRing': ['Ring', 'Rng'],
		'FI': ['B', 'FS'],
		'FinAb': ['Ab', 'Abfg'],
		'FinOrd': ['Pos', 'FinSet'],
		'FinSet': ['Set'],
		'FreeAb': ['Ab'],
		'FS': ['B', 'FI'],
		'Grp': ['Ab', 'Mon'],
		'LRS': ['Sch'],
		'Met': ['Met_oo', 'Met_c'],
		'Met_c': ['Met', 'Met_oo', 'Top'],
		'Met_oo': ['Met', 'Met_c'],
		'Mon': ['Grp'],
		'N': ['On', 'real_interval'],
		'On': ['N'],
		'On+': ['BN'],
		'R-Mod': ['Ab'],
		'real_interval': ['N'],
		'Rel': ['Set'],
		'Ring': ['CRing', 'Rng'],
		'Rng': ['Ring', 'CRing'],
		'Sch': ['LRS', 'Z'],
		'Set': ['FinSet'],
		'Setne': ['Set'],
		'Sp': ['B', 'FinSet'],
		'Vect': ['R-Mod'],
		'walking_isomorphism': ['I', '1'],
		'walking_pair': ['I'],
		'Z': ['Sch', 'Set'],
	}
