import type { CategoryID } from './categories.data'
import type { DescriptionWithReason } from './category-epimorphisms.data'

export const CATEGORY_MONOMORPHISMS: Record<CategoryID, DescriptionWithReason> = {
	'0': ["there aren't any", ''],
	'1': ['every morphism', ''],
	'2': ['every morphism', ''],
	'Ab': ['injective homomorphisms', ''],
	'Abfg': ['injective homomorphisms', ''],
	'B': ['every morphism', ''],
	'Ban': ['injective linear contractions', ''],
	'BG': ['every morphism', ''],
	'BGf': ['every morphism', ''],
	'BN': ['every morphism', ''],
	'Cat': ['faithful functors that are injective on objects', ''],
	'CRing': ['injective ring homomorphisms', ''],
	'FI': ['every morphism', ''],
	'FinAb': ['injective homomorphisms', ''],
	'FinOrd': ['injective order-preserving maps', ''],
	'FinSet': ['injective maps', ''],
	'Fld': ['every morphism', ''],
	'FreeAb': ['injective homomorphisms', ''],
	'FS': ['bijective maps', ''],
	'Grp': ['injective homomorphisms', ''],
	'I': ['every morphism', ''],
	'LRS': ['', ''],
	'M-Set': ['injective $M$-maps', ''],
	'Man': ['injective smooth maps', ''],
	'Meas': ['injective measurable maps', ''],
	'Met': ['injective non-expansive maps', ''],
	'Met_c': ['injective continuous maps', ''],
	'Met_oo': ['injective non-expansive maps', ''],
	'Mon': ['injective homomorphisms', ''],
	'N': ['every morphism', ''],
	'On': ['every morphism', ''],
	'On+': ['every ordinal number', ''],
	'Pos': ['injective order-preserving functions', ''],
	'R-Mod': ['injective $R$-linear maps', ''],
	'real_interval': ['every morphism', ''],
	'Rel': ['A relation $R : A \\to B$ is a monomorphism iff the map $R_* : P(A) \\to P(B)$ defined by $T \\mapsto \\{b \\in B : \\exists \\, a \\in T: (a,b) \\in R \\}$ is injective.', ''],
	'Ring': ['injective ring homomorphisms', ''],
	'Rng': ['injective rng homomorphisms', ''],
	'Sch': ['cf. EGA IV, 17.2.6', ''],
	'Set': ['injective maps', ''],
	'Set*': ['injective pointed maps', ''],
	'Setne': ['injective maps', ''],
	'Sp': ['pointwise injective natural transformations', ''],
	'sSet': ['pointwise injective transformations', ''],
	'Top': ['injective continuous maps', ''],
	'Vect': ['injective linear maps', ''],
	'walking_isomorphism': ['every morphism', ''],
	'walking_pair': ['every morphism', ''],
	'Z': ['objectwise injective natural transformations', ''],
}
