import type { CategoryID } from './categories.data'

export type DescriptionWithReason = {
	description: string
	reason: string
}

export const CATEGORY_EPIMORPHISMS: Record<CategoryID, DescriptionWithReason> = {
	'0': { description: "there aren't any", reason: 'trivial' },
	'1': { description: 'every morphism', reason: 'it is discrete' },
	'2': { description: 'every morphism', reason: 'it is discrete' },
	'Set': { description: 'surjective maps', reason: 'For the non-trivial direction, if $f : X \\to Y$ is an epimorphism of sets, then in particular $f^* : \\hom(Y,2) \\to \\hom(X,2)$ is injective, which identifies with $f^* : P(Y) \\to P(X)$. Then for all $y \\in Y$ we have $f^*(\\{y\\}) \\neq f^*(\\emptyset) = \\emptyset$, so that $y$ has a preimage.' },
	'Ab': { description: 'surjective homomorphisms', reason: 'For the non-trivial direction, if $f : A \\to B$ is an epimorphism, then $p \\circ f = 0$ for the projection  $p : B \\to B/f(A)$ implies that $p = 0$, so that $B = f(A)$.' },
	'Top': { description: 'surjective continuous maps', reason: 'The proof works exactly as for the category of sets, where we endow $2$ with the indiscrete topology.' },
	'Grp': { description: 'surjective homomorphisms', reason: 'For the non-trivial direction, if $f : G \\to H$ is an epimorphism, we may factor it as $G \\to f(G) \\to H$, and $f(G) \\to H$ is still an epimorphism, but also an inclusion and hence a monomorphism. Since we already know that the category is balanced, $f(G) \\to H$ must be an isomorphism.' },
	'Vect': { description: 'surjective linear maps', reason: 'The forgetful functor to abelian groups is faithful and preserves colimits, hence reflects and preserves epimorphisms. Alternatively, just use the same proof as for abelian groups.' },
	'Ring': { description: '', reason: '' },
	'CRing': { description: '', reason: '' },
	'Rng': { description: '', reason: '' },
	'FinSet': { description: 'surjective maps', reason: 'Use the same proof as for sets.' },
	'FinAb': { description: 'surjective homomorphisms', reason: 'Use the same proof as for abelian groups.' },
	'Abfg': { description: 'surjective homomorphisms', reason: 'Use the same proof as for abelian groups.' },
	'Set*': { description: 'surjective pointed maps', reason: '' },
	'sSet': { description: 'pointwise surjective transformations', reason: 'This holds in every functor category $[\\mathcal{C},\\mathbf{Set}]$.' },
	'Mon': { description: '', reason: '' },
	'Pos': { description: 'surjective order-preserving functions', reason: 'Use the same proof as for sets, where $2 = \\{0,1\\}$ is endowed with the trivial order in which $0$, $1$ have no relation.' },
	'walking_morphism': { description: 'every morphism', reason: 'It is a thin category.' },
	'M-Set': { description: 'surjective $M$-maps', reason: 'This holds in every functor category $[\\mathcal{C},\\mathbf{Set}]$, here applied to the case that $\\mathcal{C}$ has just one object.' },
	'R-Mod': { description: 'surjective $R$-linear maps', reason: 'The forgetful functor to abelian groups is faithful and preserves colimits, hence reflects and preserves epimorphisms. Alternatively, just use the same proof as for abelian groups.' },
	'Met': { description: '', reason: '' },
	'Met_oo': { description: '', reason: '' },
	'Met_c': { description: '', reason: '' },
	'Ban': { description: 'linear contractions with dense image', reason: '' },
	'Man': { description: '', reason: '' },
	'Meas': { description: 'surjective measurable maps', reason: 'Use the same proof as for sets, where $2 = \\{0,1\\}$ is endowed with the trivial $\\sigma$-algebra.' },
	'N': { description: 'every morphism', reason: 'It is a thin category.' },
	'Cat': { description: "are surjective on objects, but not necessarily on morphisms. Isbell's zigzag theorem gives a precise characterization.", reason: '' },
	'On': { description: 'every morphism', reason: 'It is a thin category.' },
	'LRS': { description: '', reason: '' },
	'Sch': { description: '', reason: '' },
	'Fld': { description: 'purely inseparable homomorphisms', reason: '' },
	'FreeAb': { description: 'homomorphisms $f : A \\to B$ with the property that $f(A)$ is not contained in a proper direct summand of $B$.', reason: '' },
	'Z': { description: 'objectwise surjective natural transformations', reason: 'This holds in every functor category $[\\mathcal{C},\\mathbf{Set}]$, here applied to the case that $\\mathcal{C}$ has just one object.' },
	'BG': { description: 'every morphism', reason: 'it is a groupoid' },
	'BGf': { description: 'every morphism', reason: 'it is a groupoid' },
	'BN': { description: 'every morphism', reason: 'Addition of natural numbers is cancellative.' },
	'walking_pair': { description: 'every morphism', reason: 'Each $0 \\to 1$ is an epimorphism since the only morphism starting at $1$ is the identity.' },
	'walking_isomorphism': { description: 'every morphism', reason: 'it is a groupoid' },
	'Setne': { description: 'surjective maps', reason: 'For the non-trivial direction, let $f : X \\to Y$ be an epimorphism of non-empty sets. Then the inclusion $f(X) \\hookrightarrow Y$ is an epimorphism as well, but also a split monomorphism (we can just map everything in $Y \\setminus f(X)$ to a fixed element of $f(X)$). As such, it must be an isomorphism.' },
	'B': { description: 'every morphism', reason: 'it is a groupoid' },
	'FI': { description: 'bijective maps', reason: '' },
	'FS': { description: 'every morphism', reason: '' },
	'On+': { description: 'finite ordinal numbers', reason: 'See <a href="https://math.stackexchange.com/questions/5029605" target="_blank">MO/5029605</a>.' },
	'FinOrd': { description: 'surjective order-preserving maps', reason: '' },
	'Rel': { description: 'A relation $R : A \\to B$ is an epimorphism iff the map $R^* : P(B) \\to P(A)$ defined by $S \\mapsto \\{a \\in A : \\exists \\, b \\in S: (a,b) \\in R \\}$ is injective.', reason: '' },
	'Sp': { description: 'pointwise surjective natural transformations', reason: 'This holds in every functor category $[\\mathcal{C},\\mathbf{Set}]$.' },
	'real_interval': { description: 'every morphism', reason: 'It is a thin category.' },
	'Zdiv': { description: 'every morphism', reason: 'It is a thin category.' },
	'Noo': { description: 'every morphism', reason: 'It is a thin category.' },
}
