import type { CategoryID } from './categories.data'
import type { PropertyID } from './properties.data'

export type PropertyWithReason = {
	id: PropertyID
	reason: string
}

export const CATEGORY_PROPERTIES: Record<CategoryID, PropertyWithReason[]> = {
	'0': [
		{ id: 'preadditive', reason: 'This is vacuously true.' },
		{ id: 'discrete', reason: 'trivial' },
		{ id: 'binary products', reason: 'This is vacuously true.' },
		{ id: 'finite', reason: 'trivial' },
	],
	'1': [
		{ id: 'trivial', reason: 'trivial' },
		{ id: 'finite', reason: 'trivial' },
		{ id: 'discrete', reason: 'trivial' },
	],
	'2': [
		{ id: 'discrete', reason: 'trivial' },
		{ id: 'finite', reason: 'trivial' },
		{ id: 'inhabited', reason: 'trivial' },
	],
	'Set': [
		{ id: 'locally small', reason: 'The collection of maps between two sets $X,Y$ is a subset of $X \\times Y$ and therefore a set.' },
		{ id: 'Grothendieck topos', reason: 'It is equivalent to the category of sheaves on a one-point space.' },
		{ id: 'finitary algebraic', reason: 'Use the empty algebraic theory.' },
	],
	'Ab': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Ab} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'abelian', reason: 'standard' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory of a commutative group.' },
	],
	'Top': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Top} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'complete', reason: 'Take the limit of the underlying sets and endow it with the coarsest topology making all projections continuous.' },
		{ id: 'cocomplete', reason: 'Take the colimit of the underlying sets and endow it with the finest topology making all inclusions continuous.' },
		{ id: 'well-powered', reason: 'This is clear from the classification of monomorphisms as injective continuous maps.' },
		{ id: 'well-copowered', reason: 'This is clear from the classification of epimorphisms as surjective continuous maps.' },
		{ id: 'infinitary distributive', reason: 'The canonical continuous map $\\coprod_i (X \\times Y_i) \\to X \\times \\coprod_{i \\in I} Y_i$ is bijective since $\\mathbf{Set}$ is infinitary distributive, and one easily checks with the definitions of product and coproduct topologies that it maps open sets to open sets.' },
		{ id: 'generator', reason: 'The one-point space is a generator since it represents the forgetful functor $\\mathbf{Top} \\to \\mathbf{Set}$.' },
		{ id: 'disjoint coproducts', reason: 'This follows easily from the corresponding fact for sets.' },
	],
	'Grp': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Grp} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'pointed', reason: 'The trivial group is a zero object.' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory of a group.' },
		{ id: 'mono-regular', reason: '' },
		{ id: 'disjoint coproducts', reason: '' },
		{ id: 'epi-regular', reason: 'This holds since every epimorphism is surjective, and surjective homomorphism $A \\to B$ is the coequalizer of its kernel pair $A \\times_B A \\rightrightarrows A$.' },
		{ id: 'Malcev', reason: 'easy; Borceux & Bourn (2004), Ex. 2.2.4' },
	],
	'Vect': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Vect} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'split abelian', reason: 'It is a fact from linear algebra that every subspace has a complement.' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory of a vector space.' },
	],
	'Ring': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Ring} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory of a ring.' },
		{ id: 'strict terminal object', reason: 'If $f : 0 \\to R$ is a homomorphism, then $R$ satisfies $1=f(1)=f(0)=0$, so that $R=0$.' },
		{ id: 'Malcev', reason: 'follows in the same way as for (additive) groups' },
	],
	'CRing': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{CRing} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory of a commutative ring.' },
		{ id: 'strict terminal object', reason: 'If $f : 0 \\to R$ is a homomorphism, then $R$ satisfies $1=f(1)=f(0)=0$, so that $R=0$.' },
		{ id: 'Malcev', reason: 'follows in the same way as for (additive) groups' },
	],
	'Rng': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Rng} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory of a rng.' },
		{ id: 'pointed', reason: 'The zero ring is a zero object.' },
		{ id: 'disjoint coproducts', reason: '' },
		{ id: 'Malcev', reason: 'follows in the same way as for (additive) groups' },
	],
	'FinSet': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{FinSet} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'essentially small', reason: 'Every finite set is isomorphic to some $[n] = \\{1,\\dotsc,n\\}$ for some $n \\in \\mathbb{N}$.' },
		{ id: 'elementary topos', reason: '' },
		{ id: 'generator', reason: 'The one-point set is a generator since it represents the forgetful functor $\\mathbf{FinSet} \\to \\mathbf{Set}$.' },
		{ id: 'cogenerator', reason: 'The two-element set is a cogenerator.' },
	],
	'FinAb': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{FinAb} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'essentially small', reason: 'The underlying set of a finite structure can be chosen to be a subset of $\\mathbb{N}$.' },
		{ id: 'abelian', reason: 'follows from the fact for abelian groups' },
		{ id: 'self-dual', reason: 'Pontrjagin duality' },
	],
	'Abfg': [
		{ id: 'locally small', reason: '' },
		{ id: 'essentially small', reason: '' },
		{ id: 'abelian', reason: '' },
		{ id: 'generator', reason: '' },
	],
	'Set*': [
		{ id: 'locally small', reason: '' },
		{ id: 'pointed', reason: '' },
		{ id: 'finitary algebraic', reason: '' },
		{ id: 'subobject classifier', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'disjoint coproducts', reason: '' },
		{ id: 'epi-regular', reason: '' },
	],
	'sSet': [
		{ id: 'locally small', reason: '' },
		{ id: 'Grothendieck topos', reason: '' },
		{ id: 'locally finitely presentable', reason: '' },
	],
	'Mon': [
		{ id: 'locally small', reason: '' },
		{ id: 'pointed', reason: '' },
		{ id: 'finitary algebraic', reason: '' },
		{ id: 'disjoint coproducts', reason: '' },
	],
	'Pos': [
		{ id: 'locally small', reason: '' },
		{ id: 'locally finitely presentable', reason: '' },
		{ id: 'cartesian closed', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'disjoint coproducts', reason: '' },
	],
	'walking_morphism': [
		{ id: 'finitary algebraic', reason: '' },
		{ id: 'self-dual', reason: '' },
		{ id: 'finite', reason: '' },
		{ id: 'cartesian closed', reason: '' },
		{ id: 'skeletal', reason: 'The two objects are not isomorphic' },
	],
	'M-Set': [
		{ id: 'locally small', reason: '' },
		{ id: 'Grothendieck topos', reason: '' },
		{ id: 'finitary algebraic', reason: '' },
	],
	'R-Mod': [
		{ id: 'locally small', reason: '' },
		{ id: 'abelian', reason: '' },
		{ id: 'finitary algebraic', reason: '' },
	],
	'Met': [
		{ id: 'locally small', reason: '' },
		{ id: 'well-powered', reason: '' },
		{ id: 'well-copowered', reason: '' },
		{ id: 'equalizers', reason: '' },
		{ id: 'finite products', reason: '' },
		{ id: 'coequalizers', reason: '' },
		{ id: 'filtered colimits', reason: '' },
		{ id: 'strict initial object', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'cogenerator', reason: '' },
	],
	'Met_oo': [
		{ id: 'locally small', reason: '' },
		{ id: 'locally ℵ₁-presentable', reason: 'Example 4.5 in <a href="https://arxiv.org/abs/1504.02660" target="_blank">this preprint</a>' },
		{ id: 'infinitary distributive', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'disjoint coproducts', reason: '' },
	],
	'Met_c': [
		{ id: 'locally small', reason: '' },
		{ id: 'equalizers', reason: '' },
		{ id: 'disjoint coproducts', reason: '' },
		{ id: 'well-powered', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'infinitary distributive', reason: '' },
		{ id: 'countable products', reason: '' },
	],
	'Ban': [
		{ id: 'locally small', reason: '' },
		{ id: 'pointed', reason: '' },
		{ id: 'locally ℵ₁-presentable', reason: 'Example 1.48 in Adamek-Rosicky' },
		{ id: 'disjoint coproducts', reason: '' },
		{ id: 'cogenerator', reason: 'Hahn-Banach shows that $\\mathbb{C}$ is one' },
	],
	'Man': [
		{ id: 'locally small', reason: '' },
		{ id: 'well-powered', reason: '' },
		{ id: 'well-copowered', reason: '' },
		{ id: 'distributive', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'disjoint finite coproducts', reason: '' },
		{ id: 'countable coproducts', reason: '' },
		{ id: 'Cauchy complete', reason: '' },
	],
	'Meas': [
		{ id: 'locally small', reason: '' },
		{ id: 'well-powered', reason: '' },
		{ id: 'well-copowered', reason: '' },
		{ id: 'complete', reason: '' },
		{ id: 'cocomplete', reason: '' },
		{ id: 'infinitary distributive', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'disjoint coproducts', reason: '' },
	],
	'N': [
		{ id: 'small', reason: '' },
		{ id: 'finitely cocomplete', reason: '' },
		{ id: 'binary products', reason: '' },
		{ id: 'thin', reason: '' },
		{ id: 'wide pullbacks', reason: '' },
		{ id: 'skeletal', reason: 'The relation $\\leq$ is antisymmetric' },
	],
	'Cat': [
		{ id: 'locally small', reason: '' },
		{ id: 'cartesian closed', reason: '' },
		{ id: 'locally finitely presentable', reason: '' },
		{ id: 'disjoint coproducts', reason: '' },
	],
	'On': [
		{ id: 'thin', reason: '' },
		{ id: 'locally small', reason: '' },
		{ id: 'cocomplete', reason: '' },
		{ id: 'binary products', reason: '' },
		{ id: 'wide pullbacks', reason: '' },
		{ id: 'well-powered', reason: '' },
		{ id: 'skeletal', reason: 'The relation $\\leq$ is antisymmetric' },
	],
	'LRS': [
		{ id: 'locally small', reason: '' },
		{ id: 'complete', reason: '' },
		{ id: 'cocomplete', reason: '' },
		{ id: 'well-powered', reason: '' },
		{ id: 'well-copowered', reason: '' },
		{ id: 'infinitary distributive', reason: '' },
		{ id: 'disjoint coproducts', reason: '' },
	],
	'Sch': [
		{ id: 'locally small', reason: '' },
		{ id: 'finitely complete', reason: '' },
		{ id: 'well-powered', reason: '' },
		{ id: 'infinitary distributive', reason: '' },
		{ id: 'disjoint coproducts', reason: '' },
	],
	'Fld': [
		{ id: 'locally small', reason: '' },
		{ id: 'filtered colimits', reason: '' },
		{ id: 'connected limits', reason: '' },
		{ id: 'inhabited', reason: '' },
		{ id: 'left cancellative', reason: '' },
		{ id: 'well-powered', reason: '' },
	],
	'FreeAb': [
		{ id: 'locally small', reason: '' },
		{ id: 'additive', reason: '' },
		{ id: 'well-powered', reason: '' },
		{ id: 'well-copowered', reason: '' },
		{ id: 'equalizers', reason: 'Subgroups of free abelian groups are free abelian.' },
		{ id: 'generator', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'disjoint coproducts', reason: '' },
		{ id: 'Malcev', reason: 'follows in the same way as for abelian groups' },
	],
	'Z': [
		{ id: 'complete', reason: '' },
		{ id: 'cocomplete', reason: '' },
		{ id: 'infinitary distributive', reason: '' },
		{ id: 'exact filtered colimits', reason: '' },
		{ id: 'disjoint coproducts', reason: '' },
		{ id: 'mono-regular', reason: '' },
		{ id: 'epi-regular', reason: '' },
	],
	'BG': [
		{ id: 'small', reason: '' },
		{ id: 'groupoid', reason: '' },
		{ id: 'connected', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'skeletal', reason: 'There is just one object' },
	],
	'BGf': [
		{ id: 'finite', reason: '' },
		{ id: 'groupoid', reason: '' },
		{ id: 'connected', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'skeletal', reason: 'There is just one object' },
	],
	'BN': [
		{ id: 'small', reason: '' },
		{ id: 'connected', reason: '' },
		{ id: 'self-dual', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'pullbacks', reason: '' },
		{ id: 'left cancellative', reason: '' },
		{ id: 'skeletal', reason: 'There is just one object' },
	],
	'walking_pair': [
		{ id: 'finite', reason: '' },
		{ id: 'self-dual', reason: '' },
		{ id: 'connected', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'filtered limits', reason: '' },
		{ id: 'left cancellative', reason: '' },
		{ id: 'skeletal', reason: 'The two objects are not isomorphic' },
	],
	'walking_isomorphism': [
		{ id: 'trivial', reason: '' },
		{ id: 'finite', reason: '' },
	],
	'Setne': [
		{ id: 'locally small', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'well-powered', reason: '' },
		{ id: 'well-copowered', reason: '' },
		{ id: 'products', reason: '' },
		{ id: 'wide pushouts', reason: '' },
		{ id: 'coequalizers', reason: '' },
		{ id: 'cartesian closed', reason: '' },
		{ id: 'mono-regular', reason: '' },
		{ id: 'epi-regular', reason: '' },
	],
	'B': [
		{ id: 'locally small', reason: '' },
		{ id: 'essentially small', reason: '' },
		{ id: 'groupoid', reason: '' },
		{ id: 'inhabited', reason: '' },
	],
	'FI': [
		{ id: 'locally small', reason: '' },
		{ id: 'initial object', reason: '' },
		{ id: 'left cancellative', reason: '' },
		{ id: 'essentially small', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'connected limits', reason: '' },
		{ id: 'mono-regular', reason: '' },
		{ id: 'epi-regular', reason: '' },
	],
	'FS': [
		{ id: 'locally small', reason: '' },
		{ id: 'essentially small', reason: '' },
		{ id: 'right cancellative', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'wide pushouts', reason: '' },
		{ id: 'coequalizers', reason: '' },
		{ id: 'mono-regular', reason: '' },
		{ id: 'epi-regular', reason: '' },
	],
	'On+': [
		{ id: 'connected', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'left cancellative', reason: '' },
		{ id: 'well-copowered', reason: '' },
		{ id: 'equalizers', reason: '' },
		{ id: 'skeletal', reason: 'There is just one object' },
	],
	'FinOrd': [
		{ id: 'essentially small', reason: '' },
		{ id: 'locally small', reason: '' },
		{ id: 'finitely complete', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'strict initial object', reason: '' },
		{ id: 'coequalizers', reason: '' },
		{ id: 'mono-regular', reason: '' },
		{ id: 'epi-regular', reason: '' },
	],
	'Rel': [
		{ id: 'locally small', reason: '' },
		{ id: 'self-dual', reason: '' },
		{ id: 'pointed', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'disjoint coproducts', reason: '' },
		{ id: 'well-powered', reason: '' },
	],
	'Sp': [
		{ id: 'elementary topos', reason: '' },
		{ id: 'essentially small', reason: '' },
	],
	'real_interval': [
		{ id: 'small', reason: '' },
		{ id: 'self-dual', reason: '' },
		{ id: 'distributive', reason: '' },
		{ id: 'locally ℵ₁-presentable', reason: 'See <a href="https://math.stackexchange.com/questions/4481902/locally-presentable-vs-compactly-presentable-categories#comment9399784_4482185" target="_blank">here</a>.' },
		{ id: 'skeletal', reason: 'The relation $\\leq$ is antisymmetric.' },
	],
	'Zdiv': [
		{ id: 'small', reason: 'trivial' },
		{ id: 'products', reason: 'Take the $\\gcd$ of a subset.' },
		{ id: 'distributive', reason: 'Using prime factorizations, one can prove that $\\gcd(a, \\mathrm{lcm} \\{b_i \\}) = \\mathrm{lcm} \\{ \\gcd(a, b_i) \\}$ for finitely many $b_i$.' },
		{
			id: 'locally ℵ₁-presentable',
			reason: 'Every $\\aleph_1$-directed diagram is eventually constant.',
		},
	],
	'Noo': [
		{ id: 'small', reason: 'trivial' },
		{ id: 'coproducts', reason: 'Take the supremum.' },
		{ id: 'skeletal', reason: 'The relation $\\leq$ is antisymmetric' },
		{ id: 'infinitary distributive', reason: 'One can show that $\\sup_i \\min(a,b_i) = \\min(a, \\sup_i b_i)$.' },
		{ id: 'locally finitely presentable', reason: 'Every natural number is finitely presentable, and $\\infty$ is the colimit of all $n < \\infty$.' },
	],
}
