import type { CategoryID } from './categories.data'
import type { PropertyID } from './properties.data'

export const CATEGORY_PROPERTIES: [CategoryID, PropertyID, string][] = [
	['Set', 'locally small', ''],
	['Set', 'Grothendieck topos', ''],
	['Set', 'finitary algebraic', ''],
	['Ab', 'locally small', ''],
	['Ab', 'abelian', ''],
	['Ab', 'finitary algebraic', ''],
	['Top', 'locally small', ''],
	['Top', 'complete', ''],
	['Top', 'cocomplete', ''],
	['Top', 'well-powered', ''],
	['Top', 'well-copowered', ''],
	['Top', 'infinitary distributive', ''],
	['Top', 'generator', ''],
	['Top', 'disjoint coproducts', ''],
	['Grp', 'locally small', ''],
	['Grp', 'pointed', ''],
	['Grp', 'finitary algebraic', ''],
	['Grp', 'mono-regular', ''],
	['Grp', 'disjoint coproducts', ''],
	['Grp', 'epi-regular', ''],
	['Vect', 'locally small', ''],
	['Vect', 'split abelian', ''],
	['Vect', 'finitary algebraic', ''],
	['Ring', 'locally small', ''],
	['Ring', 'finitary algebraic', ''],
	['Ring', 'strict terminal object', ''],
	['CRing', 'locally small', ''],
	['CRing', 'finitary algebraic', ''],
	['CRing', 'strict terminal object', ''],
	['Rng', 'locally small', ''],
	['Rng', 'finitary algebraic', ''],
	['Rng', 'pointed', ''],
	['Rng', 'disjoint coproducts', ''],
	['FinSet', 'essentially small', ''],
	['FinSet', 'locally small', ''],
	['FinSet', 'elementary topos', ''],
	['FinSet', 'generator', ''],
	['FinSet', 'cogenerator', ''],
	['FinAb', 'locally small', ''],
	['FinAb', 'essentially small', ''],
	['FinAb', 'abelian', ''],
	['FinAb', 'self-dual', ''],
	['Abfg', 'locally small', ''],
	['Abfg', 'essentially small', ''],
	['Abfg', 'abelian', ''],
	['Abfg', 'generator', ''],
	['Set*', 'locally small', ''],
	['Set*', 'pointed', ''],
	['Set*', 'finitary algebraic', ''],
	['Set*', 'subobject classifier', ''],
	['Set*', 'cogenerator', ''],
	['Set*', 'disjoint coproducts', ''],
	['Set*', 'epi-regular', ''],
	['sSet', 'locally small', ''],
	['sSet', 'Grothendieck topos', ''],
	['sSet', 'locally finitely presentable', ''],
	['Mon', 'locally small', ''],
	['Mon', 'pointed', ''],
	['Mon', 'finitary algebraic', ''],
	['Mon', 'disjoint coproducts', ''],
	['Pos', 'locally small', ''],
	['Pos', 'locally finitely presentable', ''],
	['Pos', 'cartesian closed', ''],
	['Pos', 'cogenerator', ''],
	['Pos', 'disjoint coproducts', ''],
	['0', 'preadditive', ''],
	['0', 'discrete', ''],
	['0', 'binary products', ''],
	['0', 'finite', ''],
	['1', 'trivial', ''],
	['1', 'finite', ''],
	['1', 'discrete', ''],
	['2', 'discrete', ''],
	['2', 'finite', ''],
	['2', 'inhabited', ''],
	['I', 'finitary algebraic', ''],
	['I', 'self-dual', ''],
	['I', 'finite', ''],
	['I', 'cartesian closed', ''],
	['I', 'skeletal', 'The two objects are not isomorphic'],
	['M-Set', 'locally small', ''],
	['M-Set', 'Grothendieck topos', ''],
	['M-Set', 'finitary algebraic', ''],
	['R-Mod', 'locally small', ''],
	['R-Mod', 'abelian', ''],
	['R-Mod', 'finitary algebraic', ''],
	['Met', 'locally small', ''],
	['Met', 'well-powered', ''],
	['Met', 'well-copowered', ''],
	['Met', 'equalizers', ''],
	['Met', 'finite products', ''],
	['Met', 'coequalizers', ''],
	['Met', 'filtered colimits', ''],
	['Met', 'strict initial object', ''],
	['Met', 'generator', ''],
	['Met', 'cogenerator', ''],
	['Met_oo', 'locally small', ''],
	['Met_oo', 'locally ℵ₁-presentable', '4.5 in https://arxiv.org/abs/1504.02660'],
	['Met_oo', 'infinitary distributive', ''],
	['Met_oo', 'cogenerator', ''],
	['Met_oo', 'disjoint coproducts', ''],
	['Met_c', 'locally small', ''],
	['Met_c', 'equalizers', ''],
	['Met_c', 'disjoint coproducts', ''],
	['Met_c', 'well-powered', ''],
	['Met_c', 'generator', ''],
	['Met_c', 'cogenerator', ''],
	['Met_c', 'infinitary distributive', ''],
	['Met_c', 'countable products', ''],
	['Ban', 'locally small', ''],
	['Ban', 'pointed', ''],
	['Ban', 'locally ℵ₁-presentable', 'Example 1.48 in Adamek-Rosicky'],
	['Ban', 'disjoint coproducts', ''],
	['Ban', 'cogenerator', 'Hahn-Banach shows that $\\mathbb{C}$ is one'],
	['Man', 'locally small', ''],
	['Man', 'well-powered', ''],
	['Man', 'well-copowered', ''],
	['Man', 'distributive', ''],
	['Man', 'generator', ''],
	['Man', 'disjoint finite coproducts', ''],
	['Man', 'countable coproducts', ''],
	['Man', 'Cauchy complete', ''],
	['Meas', 'locally small', ''],
	['Meas', 'well-powered', ''],
	['Meas', 'well-copowered', ''],
	['Meas', 'complete', ''],
	['Meas', 'cocomplete', ''],
	['Meas', 'infinitary distributive', ''],
	['Meas', 'generator', ''],
	['Meas', 'cogenerator', ''],
	['Meas', 'disjoint coproducts', ''],
	['N', 'small', ''],
	['N', 'finitely cocomplete', ''],
	['N', 'binary products', ''],
	['N', 'thin', ''],
	['N', 'wide pullbacks', ''],
	['N', 'skeletal', 'The relation $\\leq$ is antisymmetric'],
	['Cat', 'locally small', ''],
	['Cat', 'cartesian closed', ''],
	['Cat', 'locally finitely presentable', ''],
	['Cat', 'disjoint coproducts', ''],
	['On', 'thin', ''],
	['On', 'locally small', ''],
	['On', 'cocomplete', ''],
	['On', 'binary products', ''],
	['On', 'wide pullbacks', ''],
	['On', 'well-powered', ''],
	['On', 'skeletal', 'The relation $\\leq$ is antisymmetric'],
	['LRS', 'locally small', ''],
	['LRS', 'complete', ''],
	['LRS', 'cocomplete', ''],
	['LRS', 'well-powered', ''],
	['LRS', 'well-copowered', ''],
	['LRS', 'infinitary distributive', ''],
	['LRS', 'disjoint coproducts', ''],
	['Sch', 'locally small', ''],
	['Sch', 'finitely complete', ''],
	['Sch', 'well-powered', ''],
	['Sch', 'infinitary distributive', ''],
	['Sch', 'disjoint coproducts', ''],
	['Fld', 'locally small', ''],
	['Fld', 'filtered colimits', ''],
	['Fld', 'connected limits', ''],
	['Fld', 'inhabited', ''],
	['Fld', 'left cancellative', ''],
	['Fld', 'well-powered', ''],
	['FreeAb', 'locally small', ''],
	['FreeAb', 'additive', ''],
	['FreeAb', 'well-powered', ''],
	['FreeAb', 'well-copowered', ''],
	['FreeAb', 'equalizers', ''],
	['FreeAb', 'generator', ''],
	['FreeAb', 'cogenerator', ''],
	['FreeAb', 'disjoint coproducts', ''],
	['Z', 'complete', ''],
	['Z', 'cocomplete', ''],
	['Z', 'infinitary distributive', ''],
	['Z', 'exact filtered colimits', ''],
	['Z', 'disjoint coproducts', ''],
	['Z', 'mono-regular', ''],
	['Z', 'epi-regular', ''],
	['BG', 'small', ''],
	['BG', 'groupoid', ''],
	['BG', 'connected', ''],
	['BG', 'generator', ''],
	['BG', 'skeletal', 'There is just one object'],
	['BGf', 'finite', ''],
	['BGf', 'groupoid', ''],
	['BGf', 'connected', ''],
	['BGf', 'generator', ''],
	['BGf', 'skeletal', 'There is just one object'],
	['BN', 'small', ''],
	['BN', 'connected', ''],
	['BN', 'self-dual', ''],
	['BN', 'generator', ''],
	['BN', 'pullbacks', ''],
	['BN', 'left cancellative', ''],
	['BN', 'skeletal', 'There is just one object'],
	['walking_pair', 'finite', ''],
	['walking_pair', 'self-dual', ''],
	['walking_pair', 'connected', ''],
	['walking_pair', 'generator', ''],
	['walking_pair', 'filtered limits', ''],
	['walking_pair', 'left cancellative', ''],
	['walking_pair', 'skeletal', 'The two objects are not isomorphic'],
	['walking_isomorphism', 'trivial', ''],
	['walking_isomorphism', 'finite', ''],
	['Setne', 'locally small', ''],
	['Setne', 'generator', ''],
	['Setne', 'cogenerator', ''],
	['Setne', 'well-powered', ''],
	['Setne', 'well-copowered', ''],
	['Setne', 'products', ''],
	['Setne', 'wide pushouts', ''],
	['Setne', 'coequalizers', ''],
	['Setne', 'cartesian closed', ''],
	['Setne', 'mono-regular', ''],
	['Setne', 'epi-regular', ''],
	['B', 'locally small', ''],
	['B', 'essentially small', ''],
	['B', 'groupoid', ''],
	['B', 'inhabited', ''],
	['FI', 'locally small', ''],
	['FI', 'initial object', ''],
	['FI', 'left cancellative', ''],
	['FI', 'essentially small', ''],
	['FI', 'generator', ''],
	['FI', 'connected limits', ''],
	['FI', 'mono-regular', ''],
	['FI', 'epi-regular', ''],
	['FS', 'locally small', ''],
	['FS', 'essentially small', ''],
	['FS', 'right cancellative', ''],
	['FS', 'cogenerator', ''],
	['FS', 'wide pushouts', ''],
	['FS', 'coequalizers', ''],
	['FS', 'mono-regular', ''],
	['FS', 'epi-regular', ''],
	['On+', 'connected', ''],
	['On+', 'generator', ''],
	['On+', 'cogenerator', ''],
	['On+', 'left cancellative', ''],
	['On+', 'well-copowered', ''],
	['On+', 'equalizers', ''],
	['On+', 'skeletal', 'There is just one object'],
	['FinOrd', 'essentially small', ''],
	['FinOrd', 'locally small', ''],
	['FinOrd', 'finitely complete', ''],
	['FinOrd', 'generator', ''],
	['FinOrd', 'cogenerator', ''],
	['FinOrd', 'strict initial object', ''],
	['FinOrd', 'coequalizers', ''],
	['FinOrd', 'mono-regular', ''],
	['FinOrd', 'epi-regular', ''],
	['Rel', 'locally small', ''],
	['Rel', 'self-dual', ''],
	['Rel', 'pointed', ''],
	['Rel', 'generator', ''],
	['Rel', 'disjoint coproducts', ''],
	['Rel', 'well-powered', ''],
	['Sp', 'elementary topos', ''],
	['Sp', 'essentially small', ''],
	['real_interval', 'small', ''],
	['real_interval', 'self-dual', ''],
	['real_interval', 'distributive', ''],
	['real_interval', 'locally ℵ₁-presentable', 'https://math.stackexchange.com/questions/4481902/locally-presentable-vs-compactly-presentable-categories#comment9399784_4482185'],
	['real_interval', 'skeletal', 'The relation $\\leq$ is antisymmetric.'],
]
