import type { CategoryID } from './categories.data'
import type { PropertyWithReason } from './category-properties.data'

export const CATEGORY_NON_PROPERTIES: Record<CategoryID, PropertyWithReason[]> = {
	'0': [{ id: 'inhabited', reason: '' }],
	'1': [],
	'2': [{ id: 'connected', reason: '' }],
	'Set': [
		{ id: 'strict terminal object', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: 'There are lots of non-symmetric reflexive relations.' },
	],
	'Ab': [
		{ id: 'split abelian', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'Top': [
		{ id: 'cartesian closed', reason: '' },
		{ id: 'locally presentable', reason: '' },
		{ id: 'strict terminal object', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'exact filtered colimits', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: '' },
	],
	'Grp': [
		{ id: 'subobject classifier', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'Vect': [
		{ id: 'trivial', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'Ring': [
		{ id: 'strict initial object', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'disjoint finite coproducts', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'CRing': [
		{ id: 'strict initial object', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'disjoint finite coproducts', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'Rng': [
		{ id: 'preadditive', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'FinSet': [
		{ id: 'small', reason: '' },
		{ id: 'strict terminal object', reason: '' },
		{ id: 'sequential limits', reason: '' },
		{ id: 'sequential colimits', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: 'There are lots of non-symmetric reflexive relations.' },
	],
	'FinAb': [
		{ id: 'small', reason: 'Even the collection of trivial groups is not small.' },
		{ id: 'generator', reason: '' },
		{ id: 'split abelian', reason: 'The sequence $0 \\to \\mathbb{Z}/2 \\to \\mathbb{Z}/4 \\to \\mathbb{Z}/2 \\to 0$ does not split.' },
		{ id: 'sequential limits', reason: '' },
		{ id: 'skeletal', reason: 'There are many trivial and hence isomorphic groups, which are not equal.' },
	],
	'Abfg': [
		{ id: 'small', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'split abelian', reason: '' },
		{ id: 'countable products', reason: '' },
		{ id: 'countable coproducts', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'Set*': [
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: '' },
	],
	'sSet': [
		{ id: 'strict terminal object', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: '' },
	],
	'Mon': [
		{ id: 'preadditive', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: 'Consider the submonoid $\\{(a,b) : a \\leq b \\}$ of $\\mathbb{N}^2$.' },
	],
	'Pos': [
		{ id: 'strict terminal object', reason: '' },
		{ id: 'finitary algebraic', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: '' },
	],
	'walking_morphism': [{ id: 'subobject classifier', reason: '' }],
	'M-Set': [
		{ id: 'strict terminal object', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: '' },
	],
	'R-Mod': [
		{ id: 'split abelian', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'Met': [
		{ id: 'sequential limits', reason: '' },
		{ id: 'finite coproducts', reason: '' },
		{ id: 'strict terminal object', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'cartesian closed', reason: '' },
		{ id: 'essentially small', reason: '' },
		{ id: 'exact filtered colimits', reason: '2.7 in <a href="https://arxiv.org/abs/2006.01399" target="_blank">this paper</a>' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: '' },
	],
	'Met_oo': [
		{ id: 'strict terminal object', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'cartesian closed', reason: '' },
		{ id: 'exact filtered colimits', reason: '2.7 in <a href="https://arxiv.org/abs/2006.01399" target="_blank">this paper</a>' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: '' },
	],
	'Met_c': [
		{ id: 'products', reason: '' },
		{ id: 'strict terminal object', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'cartesian closed', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: '' },
	],
	'Ban': [
		{ id: 'preadditive', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'exact filtered colimits', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: 'See <a href="https://math.stackexchange.com/questions/5033161" target="_blank">MSE/5033161</a>.' },
	],
	'Man': [
		{ id: 'essentially small', reason: '' },
		{ id: 'countable products', reason: '' },
		{ id: 'coproducts', reason: '' },
		{ id: 'cartesian closed', reason: '' },
		{ id: 'coequalizers', reason: '' },
		{ id: 'equalizers', reason: '' },
		{ id: 'strict terminal object', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'Meas': [
		{ id: 'cartesian closed', reason: '' },
		{ id: 'strict terminal object', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: '' },
	],
	'N': [
		{ id: 'countable coproducts', reason: '' },
		{ id: 'essentially finite', reason: '' },
	],
	'Cat': [
		{ id: 'strict terminal object', reason: '' },
		{ id: 'finitary algebraic', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: '' },
	],
	'On': [
		{ id: 'terminal object', reason: '' },
		{ id: 'well-copowered', reason: '' },
	],
	'LRS': [
		{ id: 'cartesian closed', reason: '' },
		{ id: 'strict terminal object', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: 'This is because the category of schemes already is not Malcev.' },
	],
	'Sch': [
		{ id: 'coequalizers', reason: '' },
		{ id: 'countable products', reason: '' },
		{ id: 'cartesian closed', reason: '' },
		{ id: 'strict terminal object', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: 'Consider the subscheme $V(x-y) \\cup V(y) \\subseteq \\mathbb{A}^2$. It contains the diagonal but it is not symmetric.' },
	],
	'Fld': [
		{ id: 'connected', reason: '' },
		{ id: 'well-copowered', reason: '' },
		{ id: 'pushouts', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'FreeAb': [
		{ id: 'countable products', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'filtered colimits', reason: 'See <a href="https://math.stackexchange.com/questions/5025660" target="_blank">this post</a>' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'Z': [
		{ id: 'locally essentially small', reason: '' },
		{ id: 'strict terminal object', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: '' },
	],
	'BG': [
		{ id: 'zero morphisms', reason: '' },
		{ id: 'essentially finite', reason: '' },
	],
	'BGf': [{ id: 'zero morphisms', reason: '' }],
	'BN': [
		{ id: 'essentially finite', reason: '' },
		{ id: 'zero morphisms', reason: '' },
		{ id: 'equalizers', reason: '' },
		{ id: 'sequential limits', reason: '' },
	],
	'walking_pair': [
		{ id: 'initial object', reason: '' },
		{ id: 'zero morphisms', reason: '' },
		{ id: 'binary products', reason: '' },
		{ id: 'equalizers', reason: '' },
		{ id: 'pullbacks', reason: '' },
	],
	'walking_isomorphism': [{ id: 'skeletal', reason: 'The two objects are isomorphic, but different.' }],
	'Setne': [
		{ id: 'binary coproducts', reason: '' },
		{ id: 'strict terminal object', reason: '' },
		{ id: 'sequential limits', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'B': [
		{ id: 'small', reason: '' },
		{ id: 'connected', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'essentially finite', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'FI': [
		{ id: 'binary coproducts', reason: '' },
		{ id: 'small', reason: '' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'binary products', reason: '' },
		{ id: 'sequential colimits', reason: '' },
		{ id: 'essentially finite', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'FS': [
		{ id: 'small', reason: '' },
		{ id: 'connected', reason: '' },
		{ id: 'generator', reason: '' },
		{ id: 'sequential limits', reason: '' },
		{ id: 'pullbacks', reason: '' },
		{ id: 'essentially finite', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'On+': [
		{ id: 'locally essentially small', reason: '' },
		{ id: 'initial object', reason: '' },
		{ id: 'terminal object', reason: '' },
		{ id: 'right cancellative', reason: '' },
		{ id: 'zero morphisms', reason: '' },
		{ id: 'balanced', reason: '' },
		{ id: 'binary products', reason: '' },
		{ id: 'binary coproducts', reason: '' },
		{ id: 'well-powered', reason: '' },
	],
	'FinOrd': [
		{ id: 'small', reason: '' },
		{ id: 'binary coproducts', reason: '' },
		{ id: 'strict terminal object', reason: '' },
		{ id: 'subobject classifier', reason: '' },
		{ id: 'cartesian closed', reason: '' },
		{ id: 'sequential colimits', reason: '' },
		{ id: 'countable products', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: '' },
	],
	'Rel': [
		{ id: 'preadditive', reason: '' },
		{ id: 'Cauchy complete', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
	],
	'Sp': [
		{ id: 'locally small', reason: '' },
		{ id: 'strict terminal object', reason: '' },
		{ id: 'countable products', reason: '' },
		{ id: 'countable coproducts', reason: '' },
		{ id: 'skeletal', reason: 'trivial' },
		{ id: 'Malcev', reason: '' },
	],
	'real_interval': [
		{ id: 'essentially finite', reason: '' },
		{ id: 'locally finitely presentable', reason: '' },
	],
	'Zdiv': [
		{ id: 'essentially finite', reason: 'The non-negative integers are pairwise non-isomorphic in this category.' },
		{ id: 'skeletal', reason: 'The integers $+1$ and $-1$ are isomorphic, but not equal.' },
		{ id: 'self-dual', reason: 'The only integer with infinitely many divisors (up to isomorphism) is $0$. But many integers have infinitely many multiple (up to isomorphism).' },
		{ id: 'infinitary distributive', reason: 'We have $2 \\times \\coprod_n 3^n = \\gcd(2,\\mathrm{lcm}_n(3^n)) = \\gcd(2,0) = 2$, but $\\coprod_n (2 \\times 3^n) = \\mathrm{lcm}_n \\gcd(2,3^n) = \\mathrm{lcm}_n 1  = 1$.' },
	],
	'Noo': [
		{ id: 'essentially finite', reason: 'trivial' },
		{ id: 'self-dual', reason: 'every upper set is infinite, but every lower set is finite' },
	],
}
