import type { CategoryID } from './categories.data'
import type { DescriptionWithReason } from './category-epimorphisms.data'

export const CATEGORY_ISOMORPHISMS: Record<CategoryID, DescriptionWithReason> = {
	'0': { description: "there aren't any", reason: 'trivial' },
	'1': { description: 'every morphism', reason: 'trivial' },
	'2': { description: 'every morphism', reason: 'trivial' },
	'Set': { description: 'bijective maps', reason: 'easy' },
	'Ab': { description: 'bijective homomorphisms', reason: 'This characterization holds in every algebraic category.' },
	'Top': { description: 'homeomorphisms', reason: 'easy' },
	'Grp': { description: 'bijective homomorphisms', reason: 'This characterization holds in every algebraic category.' },
	'Vect': { description: 'bijective linear maps', reason: 'This characterization holds in every algebraic category.' },
	'Ring': { description: 'bijective ring homomorphisms', reason: 'This characterization holds in every algebraic category.' },
	'CRing': { description: 'bijective ring homomorphisms', reason: 'This characterization holds in every algebraic category.' },
	'Rng': { description: 'bijective rng homomorphisms', reason: 'This characterization holds in every algebraic category.' },
	'FinSet': { description: 'bijective maps', reason: 'follows exactly as for sets' },
	'FinAb': { description: 'bijective homomorphisms', reason: 'follows exactly as for abelian groups' },
	'Abfg': { description: 'bijective homomorphisms', reason: 'follows exactly as for abelian groups' },
	'Set*': { description: 'bijective pointed maps', reason: 'This characterization holds in every algebraic category.' },
	'sSet': { description: 'natural isomorphisms', reason: 'This is true for all functor categories.' },
	'Mon': { description: 'bijective homomorphisms', reason: 'This characterization holds in every algebraic category.' },
	'Pos': { description: 'bijective order-preserving and order-reflecting functions', reason: 'easy' },
	'walking_morphism': { description: 'the two identities', reason: 'trivial' },
	'M-Set': { description: 'bijective $M$-maps', reason: 'This characterization holds in every algebraic category.' },
	'R-Mod': { description: 'bijective $R$-linear maps', reason: 'This characterization holds in every algebraic category.' },
	'Met': { description: 'bijective isometries', reason: 'easy' },
	'Met_oo': { description: 'bijective isometries', reason: 'easy' },
	'Met_c': { description: 'homeomorphisms', reason: 'This works as for topological spaces.' },
	'Ban': { description: 'bijective linear isometries', reason: 'easy' },
	'Man': { description: 'diffeomorphisms', reason: 'by definition' },
	'Meas': { description: 'bijective measurable maps that map measurable sets to measurable sets', reason: 'easy' },
	'N': { description: 'only the identity morphisms', reason: 'This is true for every poset (regarded as a category).' },
	'Cat': { description: 'functors that are bijective on objects and morphisms', reason: 'easy' },
	'On': { description: 'only the identities', reason: 'This is true for every poset (regarded as a category).' },
	'LRS': { description: 'pairs $(f,f^{\\sharp})$ consisting of a homeomorphism $f$ and an isomorphism of sheaves $f^{\\sharp}$', reason: 'easy' },
	'Sch': { description: 'pairs $(f,f^{\\sharp})$ consisting of a homeomorphism $f$ and an isomorphism of sheaves $f^{\\sharp}$', reason: 'easy' },
	'Fld': { description: 'bijective field homomorphisms', reason: 'easy' },
	'FreeAb': { description: 'bijective homomorphisms', reason: 'follows exactly as for abelian groups' },
	'Z': { description: 'natural isomorphisms', reason: 'This is true for all functor categories.' },
	'BG': { description: 'every morphism', reason: 'It is a groupoid.' },
	'BGf': { description: 'every morphism', reason: 'It is a groupoid.' },
	'BN': { description: 'only the number $0$', reason: 'The $0$ is the only natural number which has an additive inverse, since for $n > 0$ we have $n + m > 0$ for all $m$.' },
	'walking_pair': { description: 'the two identities', reason: 'trivial' },
	'walking_isomorphism': { description: 'every morphism', reason: 'trivial' },
	'Setne': { description: 'bijective maps', reason: 'follows exactly as for sets' },
	'B': { description: 'every morphism', reason: 'It is a groupoid by construction.' },
	'FI': { description: 'bijective maps', reason: 'follows exactly as for sets' },
	'FS': { description: 'bijective maps', reason: 'follows exactly as for sets' },
	'On+': { description: 'only the ordinal $0$', reason: 'The $0$ is the only ordinal which has an additive inverse, since for $\\alpha > 0$ we have $\\alpha + \\beta > 0$ for all $\\beta$.' },
	'FinOrd': { description: 'bijective order-preserving maps', reason: 'This works as for posets, using that injective order-preserving maps must be order-reflecting.' },
	'Rel': { description: 'bijective functions', reason: "For the non-trivial direction, assume that $R : A \\to B$ is a relation which has an inverse relation $S : B \\to A$. For every $a \\in A$ we have $(a,a) \\in \\mathrm{id}_A = S \\circ R$, so there is some $b \\in B$ with $(a,b) \\in R$ (and $(b,a) \\in S$). This shows that $R$ is left-total, and for right-total the argument is similar. By symmetry, this also holds for $S$. To show that $R$ is a function, assume $(a,b), (a,b') \\in R$. Choose some $b'' \\in B$ with $(b'',a) \\in S$. It follows $(b'',b) \\in S \\circ R = \\mathrm{id}_A$, so $b'' = b$. Similarly, $(b'',b') \\in S \\circ R = \\mathrm{id}_A$, so $b'' = b'$. This shows that $R$ is a function, i.e. left-unique. That $R$ is injective, i.e. right-unique, follows by symmetry. Finally, $R$ is surjective since it is right-total." },
	'Sp': { description: 'natural isomorphisms', reason: 'This is the for every functor category.' },
	'real_interval': { description: 'only the identity morphisms', reason: 'This is true for every poset (regarded as a category).' },
	'Zdiv': { description: 'the identities $(a,a) : a \\to a$ and the isomorphisms $(a,-a) : a \\to -a$ for $a \\in \\mathbb{Z}$', reason: 'trivial' },
	'Noo': { description: 'only the identity morphisms', reason: 'This is true for every poset (regarded as a category).' },
}
