import type { NonEmptyArray } from '$lib/commons/utils'
import type { CategoryID } from './categories.data'
import type { Tag } from './tags.data'

export const CATEGORY_TAGS: Record<CategoryID, NonEmptyArray<Tag>> = {
	'0': ['basic', 'badly-behaved'],
	'1': ['basic', 'well-behaved'],
	'2': ['basic', 'badly-behaved'],
	'Set': ['basic', 'set theory', 'well-behaved'],
	'Ab': ['basic', 'algebra', 'well-behaved'],
	'Top': ['basic', 'topology', 'well-behaved'],
	'Grp': ['basic', 'algebra', 'well-behaved'],
	'Vect': ['basic', 'algebra', 'well-behaved'],
	'Ring': ['basic', 'algebra', 'well-behaved'],
	'CRing': ['basic', 'algebra', 'well-behaved'],
	'Rng': ['basic', 'algebra', 'well-behaved'],
	'FinSet': ['basic', 'set theory', 'well-behaved'],
	'FinAb': ['basic', 'algebra', 'badly-behaved'],
	'Abfg': ['basic', 'algebra', 'badly-behaved'],
	'Set*': ['basic', 'set theory', 'well-behaved'],
	'sSet': ['basic', 'topology', 'well-behaved'],
	'Mon': ['basic', 'algebra', 'well-behaved'],
	'Pos': ['basic', 'order theory', 'well-behaved'],
	'walking_morphism': ['basic', 'well-behaved'],
	'M-Set': ['basic', 'algebra', 'geometry', 'well-behaved'],
	'R-Mod': ['basic', 'algebra', 'well-behaved'],
	'Met': ['basic', 'geometry', 'badly-behaved'],
	'Met_oo': ['basic', 'geometry', 'well-behaved'],
	'Met_c': ['basic', 'geometry', 'badly-behaved'],
	'Ban': ['intermediate', 'analysis', 'well-behaved'],
	'Man': ['geometry', 'topology', 'badly-behaved'],
	'Meas': ['basic', 'measure theory', 'well-behaved'],
	'N': ['basic', 'number theory', 'badly-behaved'],
	'Cat': ['intermediate', 'category theory', 'well-behaved'],
	'On': ['intermediate', 'artificial', 'set theory'],
	'LRS': ['intermediate', 'algebraic geometry', 'well-behaved'],
	'Sch': ['intermediate', 'algebraic geometry', 'badly-behaved'],
	'Fld': ['basic', 'algebra', 'badly-behaved'],
	'FreeAb': ['artificial', 'basic', 'algebra', 'badly-behaved'],
	'Z': ['intermediate', 'algebraic geometry', 'well-behaved'],
	'BG': ['basic', 'algebra', 'category theory', 'badly-behaved'],
	'BGf': ['basic', 'algebra', 'category theory', 'badly-behaved'],
	'BN': ['basic', 'algebra', 'category theory', 'badly-behaved'],
	'walking_pair': ['artificial', 'category theory', 'badly-behaved'],
	'walking_isomorphism': ['artificial', 'category theory', 'badly-behaved'],
	'Setne': ['artificial', 'set theory', 'well-behaved'],
	'B': ['basic', 'set theory', 'combinatorics', 'badly-behaved'],
	'FI': ['basic', 'set theory', 'representation theory', 'badly-behaved'],
	'FS': ['basic', 'set theory', 'representation theory', 'badly-behaved'],
	'On+': ['intermediate', 'set theory', 'badly-behaved', 'artificial'],
	'FinOrd': ['basic', 'topology', 'order theory', 'badly-behaved'],
	'Rel': ['basic', 'set theory', 'well-behaved'],
	'Sp': ['intermediate', 'combinatorics'],
	'real_interval': ['basic', 'analysis', 'well-behaved'],
	'Zdiv': ['basic', 'number theory', 'well-behaved'],
	'Noo': ['basic', 'number theory', 'well-behaved'],
}
