import type { CategoryID } from './categories.data'
import type { PropertyID } from './properties.data'

// format: {category_id: [[property_id, reason why the property is not safisfied], ...]}

export const CATEGORY_NON_PROPERTIES: Record<CategoryID, [PropertyID, string][]> = {
	'0': [['inhabited', '']],
	'1': [],
	'2': [['connected', '']],
	'Set': [
		['strict terminal object', ''],
		['skeletal', 'trivial'],
		['Malcev', 'There are lots of non-symmetric reflexive relations.'],
	],
	'Ab': [
		['split abelian', ''],
		['skeletal', 'trivial'],
	],
	'Top': [
		['cartesian closed', ''],
		['locally presentable', ''],
		['strict terminal object', ''],
		['balanced', ''],
		['cogenerator', ''],
		['exact filtered colimits', ''],
		['skeletal', 'trivial'],
		['Malcev', ''],
	],
	'Grp': [
		['subobject classifier', ''],
		['cogenerator', ''],
		['skeletal', 'trivial'],
	],
	'Vect': [
		['trivial', ''],
		['skeletal', 'trivial'],
	],
	'Ring': [
		['strict initial object', ''],
		['balanced', ''],
		['cogenerator', ''],
		['disjoint finite coproducts', ''],
		['skeletal', 'trivial'],
	],
	'CRing': [
		['strict initial object', ''],
		['balanced', ''],
		['cogenerator', ''],
		['disjoint finite coproducts', ''],
		['skeletal', 'trivial'],
	],
	'Rng': [
		['preadditive', ''],
		['balanced', ''],
		['cogenerator', ''],
		['skeletal', 'trivial'],
	],
	'FinSet': [
		['small', ''],
		['strict terminal object', ''],
		['sequential limits', ''],
		['sequential colimits', ''],
		['skeletal', 'trivial'],
		['Malcev', 'There are lots of non-symmetric reflexive relations.'],
	],
	'FinAb': [
		['small', ''],
		['generator', ''],
		['split abelian', ''],
		['sequential limits', ''],
		['skeletal', 'trivial'],
	],
	'Abfg': [
		['small', ''],
		['cogenerator', ''],
		['split abelian', ''],
		['countable products', ''],
		['countable coproducts', ''],
		['skeletal', 'trivial'],
	],
	'Set*': [
		['skeletal', 'trivial'],
		['Malcev', ''],
	],
	'sSet': [
		['strict terminal object', ''],
		['skeletal', 'trivial'],
		['Malcev', ''],
	],
	'Mon': [
		['preadditive', ''],
		['balanced', ''],
		['cogenerator', ''],
		['skeletal', 'trivial'],
		['Malcev', 'Consider the submonoid $\\{(a,b) : a \\leq b \}$ of $\\mathbb{N}^2$.'],
	],
	'Pos': [
		['strict terminal object', ''],
		['finitary algebraic', ''],
		['balanced', ''],
		['skeletal', 'trivial'],
		['Malcev', ''],
	],
	'I': [['subobject classifier', '']],
	'M-Set': [
		['strict terminal object', ''],
		['skeletal', 'trivial'],
		['Malcev', ''],
	],
	'R-Mod': [
		['split abelian', ''],
		['skeletal', 'trivial'],
	],
	'Met': [
		['sequential limits', ''],
		['finite coproducts', ''],
		['strict terminal object', ''],
		['balanced', ''],
		['cartesian closed', ''],
		['essentially small', ''],
		['exact filtered colimits', '2.7 in https://arxiv.org/abs/2006.01399'],
		['skeletal', 'trivial'],
		['Malcev', ''],
	],
	'Met_oo': [
		['strict terminal object', ''],
		['balanced', ''],
		['cartesian closed', ''],
		['exact filtered colimits', '2.7 in https://arxiv.org/abs/2006.01399'],
		['skeletal', 'trivial'],
		['Malcev', ''],
	],
	'Met_c': [
		['products', ''],
		['strict terminal object', ''],
		['balanced', ''],
		['cartesian closed', ''],
		['skeletal', 'trivial'],
		['Malcev', ''],
	],
	'Ban': [
		['preadditive', ''],
		['balanced', ''],
		['exact filtered colimits', ''],
		['skeletal', 'trivial'],
	],
	'Man': [
		['essentially small', ''],
		['countable products', ''],
		['coproducts', ''],
		['cartesian closed', ''],
		['coequalizers', ''],
		['equalizers', ''],
		['strict terminal object', ''],
		['balanced', ''],
		['skeletal', 'trivial'],
	],
	'Meas': [
		['cartesian closed', ''],
		['strict terminal object', ''],
		['balanced', ''],
		['skeletal', 'trivial'],
		['Malcev', ''],
	],
	'N': [
		['countable coproducts', ''],
		['essentially finite', ''],
	],
	'Cat': [
		['strict terminal object', ''],
		['finitary algebraic', ''],
		['balanced', ''],
		['cogenerator', ''],
		['skeletal', 'trivial'],
		['Malcev', ''],
	],
	'On': [
		['terminal object', ''],
		['well-copowered', ''],
	],
	'LRS': [
		['cartesian closed', ''],
		['strict terminal object', ''],
		['skeletal', 'trivial'],
		['Malcev', 'This is because the category of schemes already is not Malcev.'],
	],
	'Sch': [
		['coequalizers', ''],
		['countable products', ''],
		['cartesian closed', ''],
		['strict terminal object', ''],
		['skeletal', 'trivial'],
		['Malcev', 'Consider the subscheme $V(x-y) \\cup V(y) \\subseteq \\mathbb{A}^2$. It contains the diagonal but it is not symmetric.'],
	],
	'Fld': [
		['connected', ''],
		['well-copowered', ''],
		['pushouts', ''],
		['balanced', ''],
		['generator', ''],
		['cogenerator', ''],
		['skeletal', 'trivial'],
	],
	'FreeAb': [
		['countable products', ''],
		['balanced', ''],
		['filtered colimits', 'https://math.stackexchange.com/questions/5025660'],
		['skeletal', 'trivial'],
	],
	'Z': [
		['locally essentially small', ''],
		['strict terminal object', ''],
		['skeletal', 'trivial'],
		['Malcev', ''],
	],
	'BG': [
		['zero morphisms', ''],
		['essentially finite', ''],
	],
	'BGf': [['zero morphisms', '']],
	'BN': [
		['essentially finite', ''],
		['zero morphisms', ''],
		['equalizers', ''],
		['sequential limits', ''],
	],
	'walking_pair': [
		['initial object', ''],
		['zero morphisms', ''],
		['binary products', ''],
		['equalizers', ''],
		['pullbacks', ''],
	],
	'walking_isomorphism': [['skeletal', 'The two objects are isomorphic, but different.']],
	'Setne': [
		['binary coproducts', ''],
		['strict terminal object', ''],
		['sequential limits', ''],
		['skeletal', 'trivial'],
	],
	'B': [
		['small', ''],
		['connected', ''],
		['generator', ''],
		['essentially finite', ''],
		['skeletal', 'trivial'],
	],
	'FI': [
		['binary coproducts', ''],
		['small', ''],
		['cogenerator', ''],
		['binary products', ''],
		['sequential colimits', ''],
		['essentially finite', ''],
		['skeletal', 'trivial'],
	],
	'FS': [
		['small', ''],
		['connected', ''],
		['generator', ''],
		['sequential limits', ''],
		['pullbacks', ''],
		['essentially finite', ''],
		['skeletal', 'trivial'],
	],
	'On+': [
		['locally essentially small', ''],
		['initial object', ''],
		['terminal object', ''],
		['right cancellative', ''],
		['zero morphisms', ''],
		['balanced', ''],
		['binary products', ''],
		['binary coproducts', ''],
		['well-powered', ''],
	],
	'FinOrd': [
		['small', ''],
		['binary coproducts', ''],
		['strict terminal object', ''],
		['subobject classifier', ''],
		['cartesian closed', ''],
		['sequential colimits', ''],
		['countable products', ''],
		['skeletal', 'trivial'],
		['Malcev', ''],
	],
	'Rel': [
		['preadditive', ''],
		['Cauchy complete', ''],
		['skeletal', 'trivial'],
	],
	'Sp': [
		['locally small', ''],
		['strict terminal object', ''],
		['countable products', ''],
		['countable coproducts', ''],
		['skeletal', 'trivial'],
		['Malcev', ''],
	],
	'real_interval': [
		['essentially finite', ''],
		['locally finitely presentable', ''],
	],
	'Zdiv': [
		['essentially finite', 'The non-negative integers are pairwise non-isomorphic in this category.'],
		['skeletal', 'The integers $+1$ and $-1$ are isomorphic, but not equal.'],
		['self-dual', 'The only integer with infinitely many divisors (up to isomorphism) is $0$. But many integers have infinitely many multiple (up to isomorphism).'],
		['infinitary distributive', 'We have $2 \\times \\coprod_n 3^n = \\gcd(2,\\mathrm{lcm}_n(3^n)) = \\gcd(2,0) = 2$, but $\\coprod_n (2 \\times 3^n) = \\mathrm{lcm}_n \\gcd(2,3^n) = \\mathrm{lcm}_n 1  = 1$.'],
	],
}
