import type { CategoryID } from './categories.data'

export type DescriptionWithReason = [string, string]

export const CATEGORY_EPIMORPHISMS: Record<CategoryID, DescriptionWithReason> = {
	'0': ["there aren't any", ''],
	'1': ['every morphism', ''],
	'2': ['every morphism', ''],
	'Ab': ['surjective homomorphisms', ''],
	'Abfg': ['surjective homomorphisms', ''],
	'B': ['every morphism', ''],
	'Ban': ['linear contractions with dense image', ''],
	'BG': ['every morphism', ''],
	'BGf': ['every morphism', ''],
	'BN': ['every morphism', ''],
	'Cat': ["are surjective on objects, but not necessarily on morphisms. Isbell's zigzag theorem gives a precise characterization.", ''],
	'CRing': ['are not necessarily surjective', ''],
	'FI': ['bijective maps', ''],
	'FinAb': ['surjective homomorphisms', ''],
	'FinOrd': ['surjective order-preserving maps', ''],
	'FinSet': ['surjective maps', ''],
	'Fld': ['purely inseparable homomorphisms', ''],
	'FreeAb': ['homomorphisms $f : A \\to B$ with the property that $f(A)$ is not contained in a proper direct summand of $B$.', ''],
	'FS': ['every morphism', ''],
	'Grp': ['surjective homomorphisms', ''],
	'I': ['every morphism', ''],
	'LRS': ['', ''],
	'M-Set': ['surjective $M$-maps', ''],
	'Man': ['are not necessarily surjective. TODO: make this more precise', ''],
	'Meas': ['surjective measurable maps', ''],
	'Met': ['are not necessarily surjective. TODO: make this more precise', ''],
	'Met_c': ['are not necessarily surjective. TODO: make this more precise', ''],
	'Met_oo': ['are not necessarily surjective. TODO: make this more precise', ''],
	'Mon': ['are not necessarily surjective', ''],
	'N': ['every morphism', ''],
	'On': ['every morphism', ''],
	'On+': ['finite ordinal numbers', ''],
	'Pos': ['surjective order-preserving functions', ''],
	'R-Mod': ['surjective $R$-linear maps', ''],
	'real_interval': ['every morphism', ''],
	'Rel': ['A relation $R : A \\to B$ is an epimorphism iff the map $R^* : P(B) \\to P(A)$ defined by $S \\mapsto \\{a \\in A : \\exists \\, b \\in S: (a,b) \\in R \\}$ is injective.', ''],
	'Ring': ['are not necessarily surjective', ''],
	'Rng': ['are not necessarily surjective', ''],
	'Sch': ['', ''],
	'Set': ['surjective maps', ''],
	'Set*': ['surjective pointed maps', ''],
	'Setne': ['surjective maps', ''],
	'Sp': ['pointwise surjective natural transformations', ''],
	'sSet': ['pointwise surjective transformations', ''],
	'Top': ['surjective continuous maps', ''],
	'Vect': ['surjective linear maps', ''],
	'walking_isomorphism': ['every morphism', ''],
	'walking_pair': ['every morphism', ''],
	'Z': ['objectwise surjective natural transformations', ''],
}
