import type { CategoryID } from './categories.data'
import type { PropertyID } from './properties.data'

// format: {category_id: [[property_id, reason why the property is safisfied], ...]}

export const CATEGORY_PROPERTIES: Record<CategoryID, [PropertyID, string][]> = {
	'0': [
		['preadditive', ''],
		['discrete', ''],
		['binary products', ''],
		['finite', ''],
	],
	'1': [
		['trivial', ''],
		['finite', ''],
		['discrete', ''],
	],
	'2': [
		['discrete', ''],
		['finite', ''],
		['inhabited', ''],
	],
	'Set': [
		['locally small', ''],
		['Grothendieck topos', ''],
		['finitary algebraic', ''],
	],
	'Ab': [
		['locally small', ''],
		['abelian', ''],
		['finitary algebraic', ''],
	],
	'Top': [
		['locally small', ''],
		['complete', ''],
		['cocomplete', ''],
		['well-powered', ''],
		['well-copowered', ''],
		['infinitary distributive', ''],
		['generator', ''],
		['disjoint coproducts', ''],
	],
	'Grp': [
		['locally small', ''],
		['pointed', ''],
		['finitary algebraic', ''],
		['mono-regular', ''],
		['disjoint coproducts', ''],
		['epi-regular', ''],
		['Malcev', 'easy; Borceux & Bourn (2004), Ex. 2.2.4'],
	],
	'Vect': [
		['locally small', ''],
		['split abelian', ''],
		['finitary algebraic', ''],
	],
	'Ring': [
		['locally small', ''],
		['finitary algebraic', ''],
		['strict terminal object', ''],
		['Malcev', 'follows in the same way as for (additive) groups'],
	],
	'CRing': [
		['locally small', ''],
		['finitary algebraic', ''],
		['strict terminal object', ''],
		['Malcev', 'follows in the same way as for (additive) groups'],
	],
	'Rng': [
		['locally small', ''],
		['finitary algebraic', ''],
		['pointed', ''],
		['disjoint coproducts', ''],
		['Malcev', 'follows in the same way as for (additive) groups'],
	],
	'FinSet': [
		['essentially small', ''],
		['locally small', ''],
		['elementary topos', ''],
		['generator', ''],
		['cogenerator', ''],
	],
	'FinAb': [
		['locally small', ''],
		['essentially small', ''],
		['abelian', ''],
		['self-dual', ''],
	],
	'Abfg': [
		['locally small', ''],
		['essentially small', ''],
		['abelian', ''],
		['generator', ''],
	],
	'Set*': [
		['locally small', ''],
		['pointed', ''],
		['finitary algebraic', ''],
		['subobject classifier', ''],
		['cogenerator', ''],
		['disjoint coproducts', ''],
		['epi-regular', ''],
	],
	'sSet': [
		['locally small', ''],
		['Grothendieck topos', ''],
		['locally finitely presentable', ''],
	],
	'Mon': [
		['locally small', ''],
		['pointed', ''],
		['finitary algebraic', ''],
		['disjoint coproducts', ''],
	],
	'Pos': [
		['locally small', ''],
		['locally finitely presentable', ''],
		['cartesian closed', ''],
		['cogenerator', ''],
		['disjoint coproducts', ''],
	],
	'I': [
		['finitary algebraic', ''],
		['self-dual', ''],
		['finite', ''],
		['cartesian closed', ''],
		['skeletal', 'The two objects are not isomorphic'],
	],
	'M-Set': [
		['locally small', ''],
		['Grothendieck topos', ''],
		['finitary algebraic', ''],
	],
	'R-Mod': [
		['locally small', ''],
		['abelian', ''],
		['finitary algebraic', ''],
	],
	'Met': [
		['locally small', ''],
		['well-powered', ''],
		['well-copowered', ''],
		['equalizers', ''],
		['finite products', ''],
		['coequalizers', ''],
		['filtered colimits', ''],
		['strict initial object', ''],
		['generator', ''],
		['cogenerator', ''],
	],
	'Met_oo': [
		['locally small', ''],
		['locally ℵ₁-presentable', '4.5 in https://arxiv.org/abs/1504.02660'],
		['infinitary distributive', ''],
		['cogenerator', ''],
		['disjoint coproducts', ''],
	],
	'Met_c': [
		['locally small', ''],
		['equalizers', ''],
		['disjoint coproducts', ''],
		['well-powered', ''],
		['generator', ''],
		['cogenerator', ''],
		['infinitary distributive', ''],
		['countable products', ''],
	],
	'Ban': [
		['locally small', ''],
		['pointed', ''],
		['locally ℵ₁-presentable', 'Example 1.48 in Adamek-Rosicky'],
		['disjoint coproducts', ''],
		['cogenerator', 'Hahn-Banach shows that $\\mathbb{C}$ is one'],
	],
	'Man': [
		['locally small', ''],
		['well-powered', ''],
		['well-copowered', ''],
		['distributive', ''],
		['generator', ''],
		['disjoint finite coproducts', ''],
		['countable coproducts', ''],
		['Cauchy complete', ''],
	],
	'Meas': [
		['locally small', ''],
		['well-powered', ''],
		['well-copowered', ''],
		['complete', ''],
		['cocomplete', ''],
		['infinitary distributive', ''],
		['generator', ''],
		['cogenerator', ''],
		['disjoint coproducts', ''],
	],
	'N': [
		['small', ''],
		['finitely cocomplete', ''],
		['binary products', ''],
		['thin', ''],
		['wide pullbacks', ''],
		['skeletal', 'The relation $\\leq$ is antisymmetric'],
	],
	'Cat': [
		['locally small', ''],
		['cartesian closed', ''],
		['locally finitely presentable', ''],
		['disjoint coproducts', ''],
	],
	'On': [
		['thin', ''],
		['locally small', ''],
		['cocomplete', ''],
		['binary products', ''],
		['wide pullbacks', ''],
		['well-powered', ''],
		['skeletal', 'The relation $\\leq$ is antisymmetric'],
	],
	'LRS': [
		['locally small', ''],
		['complete', ''],
		['cocomplete', ''],
		['well-powered', ''],
		['well-copowered', ''],
		['infinitary distributive', ''],
		['disjoint coproducts', ''],
	],
	'Sch': [
		['locally small', ''],
		['finitely complete', ''],
		['well-powered', ''],
		['infinitary distributive', ''],
		['disjoint coproducts', ''],
	],
	'Fld': [
		['locally small', ''],
		['filtered colimits', ''],
		['connected limits', ''],
		['inhabited', ''],
		['left cancellative', ''],
		['well-powered', ''],
	],
	'FreeAb': [
		['locally small', ''],
		['additive', ''],
		['well-powered', ''],
		['well-copowered', ''],
		['equalizers', 'Subgroups of free abelian groups are free abelian.'],
		['generator', ''],
		['cogenerator', ''],
		['disjoint coproducts', ''],
		['Malcev', 'follows in the same way as for abelian groups'],
	],
	'Z': [
		['complete', ''],
		['cocomplete', ''],
		['infinitary distributive', ''],
		['exact filtered colimits', ''],
		['disjoint coproducts', ''],
		['mono-regular', ''],
		['epi-regular', ''],
	],
	'BG': [
		['small', ''],
		['groupoid', ''],
		['connected', ''],
		['generator', ''],
		['skeletal', 'There is just one object'],
	],
	'BGf': [
		['finite', ''],
		['groupoid', ''],
		['connected', ''],
		['generator', ''],
		['skeletal', 'There is just one object'],
	],
	'BN': [
		['small', ''],
		['connected', ''],
		['self-dual', ''],
		['generator', ''],
		['pullbacks', ''],
		['left cancellative', ''],
		['skeletal', 'There is just one object'],
	],
	'walking_pair': [
		['finite', ''],
		['self-dual', ''],
		['connected', ''],
		['generator', ''],
		['filtered limits', ''],
		['left cancellative', ''],
		['skeletal', 'The two objects are not isomorphic'],
	],
	'walking_isomorphism': [
		['trivial', ''],
		['finite', ''],
	],
	'Setne': [
		['locally small', ''],
		['generator', ''],
		['cogenerator', ''],
		['well-powered', ''],
		['well-copowered', ''],
		['products', ''],
		['wide pushouts', ''],
		['coequalizers', ''],
		['cartesian closed', ''],
		['mono-regular', ''],
		['epi-regular', ''],
	],
	'B': [
		['locally small', ''],
		['essentially small', ''],
		['groupoid', ''],
		['inhabited', ''],
	],
	'FI': [
		['locally small', ''],
		['initial object', ''],
		['left cancellative', ''],
		['essentially small', ''],
		['generator', ''],
		['connected limits', ''],
		['mono-regular', ''],
		['epi-regular', ''],
	],
	'FS': [
		['locally small', ''],
		['essentially small', ''],
		['right cancellative', ''],
		['cogenerator', ''],
		['wide pushouts', ''],
		['coequalizers', ''],
		['mono-regular', ''],
		['epi-regular', ''],
	],
	'On+': [
		['connected', ''],
		['generator', ''],
		['cogenerator', ''],
		['left cancellative', ''],
		['well-copowered', ''],
		['equalizers', ''],
		['skeletal', 'There is just one object'],
	],
	'FinOrd': [
		['essentially small', ''],
		['locally small', ''],
		['finitely complete', ''],
		['generator', ''],
		['cogenerator', ''],
		['strict initial object', ''],
		['coequalizers', ''],
		['mono-regular', ''],
		['epi-regular', ''],
	],
	'Rel': [
		['locally small', ''],
		['self-dual', ''],
		['pointed', ''],
		['generator', ''],
		['disjoint coproducts', ''],
		['well-powered', ''],
	],
	'Sp': [
		['elementary topos', ''],
		['essentially small', ''],
	],
	'real_interval': [
		['small', ''],
		['self-dual', ''],
		['distributive', ''],
		['locally ℵ₁-presentable', 'https://math.stackexchange.com/questions/4481902/locally-presentable-vs-compactly-presentable-categories#comment9399784_4482185'],
		['skeletal', 'The relation $\\leq$ is antisymmetric.'],
	],
}
