import type { PropertyID } from './properties.data'

export const PROPERTY_DUALS: Record<PropertyID, PropertyID | null> = {
	'small': 'small',
	'locally small': 'locally small',
	'locally essentially small': 'locally essentially small',
	'complete': 'cocomplete',
	'cocomplete': 'complete',
	'cartesian closed': null,
	'zero morphisms': 'zero morphisms',
	'preadditive': 'preadditive',
	'additive': 'additive',
	'abelian': 'abelian',
	'finitely complete': 'finitely cocomplete',
	'finitely cocomplete': 'finitely complete',
	'pointed': 'pointed',
	'locally finitely presentable': null,
	'locally presentable': null,
	'locally ℵ₁-presentable': null,
	'elementary topos': null,
	'Grothendieck topos': null,
	'well-powered': 'well-copowered',
	'well-copowered': 'well-powered',
	'initial object': 'terminal object',
	'terminal object': 'initial object',
	'products': 'coproducts',
	'coproducts': 'products',
	'finite products': 'finite coproducts',
	'finite coproducts': 'finite products',
	'binary products': 'binary coproducts',
	'binary coproducts': 'binary products',
	'countable products': 'countable coproducts',
	'countable coproducts': 'countable products',
	'equalizers': 'coequalizers',
	'coequalizers': 'equalizers',
	'filtered limits': 'filtered colimits',
	'filtered colimits': 'filtered limits',
	'sequential limits': 'sequential colimits',
	'sequential colimits': 'sequential limits',
	'connected limits': 'connected colimits',
	'connected colimits': 'connected limits',
	'strict initial object': 'strict terminal object',
	'strict terminal object': 'strict initial object',
	'self-dual': 'self-dual',
	'groupoid': 'groupoid',
	'essentially small': 'essentially small',
	'thin': 'thin',
	'discrete': 'discrete',
	'essentially discrete': 'essentially discrete',
	'finitary algebraic': null,
	'finite': 'finite',
	'essentially finite': 'essentially finite',
	'connected': 'connected',
	'pullbacks': 'pushouts',
	'pushouts': 'pullbacks',
	'trivial': 'trivial',
	'inhabited': 'inhabited',
	'subobject classifier': null,
	'balanced': 'balanced',
	'infinitary distributive': null,
	'distributive': null,
	'generator': 'cogenerator',
	'cogenerator': 'generator',
	'exact filtered colimits': null,
	'Grothendieck abelian': null,
	'disjoint finite coproducts': null,
	'disjoint coproducts': null,
	'left cancellative': 'right cancellative',
	'right cancellative': 'left cancellative',
	'wide pullbacks': 'wide pushouts',
	'wide pushouts': 'wide pullbacks',
	'split abelian': 'split abelian',
	'Cauchy complete': 'Cauchy complete',
	'mono-regular': 'epi-regular',
	'epi-regular': 'mono-regular',
	'skeletal': 'skeletal',
	'Malcev': null,
}
