import type { PropertyID } from './properties.data'

export const PROPERTY_RELATIONS: Record<PropertyID, PropertyID[]> = {
	'small': ['essentially small'],
	'locally small': ['locally essentially small'],
	'locally essentially small': ['locally small'],
	'complete': [],
	'cocomplete': [],
	'cartesian closed': ['finite products'],
	'zero morphisms': ['preadditive', 'pointed'],
	'preadditive': ['additive'],
	'additive': ['preadditive', 'finite products'],
	'abelian': ['additive'],
	'finitely complete': ['complete'],
	'finitely cocomplete': ['cocomplete'],
	'pointed': ['initial object', 'terminal object'],
	'locally finitely presentable': ['locally presentable', 'locally ℵ₁-presentable'],
	'locally presentable': ['locally finitely presentable', 'locally ℵ₁-presentable'],
	'locally ℵ₁-presentable': ['locally finitely presentable', 'locally presentable'],
	'elementary topos': ['Grothendieck topos'],
	'Grothendieck topos': ['elementary topos'],
	'well-powered': [],
	'well-copowered': [],
	'initial object': ['finite coproducts'],
	'terminal object': ['finite coproducts'],
	'products': ['complete'],
	'coproducts': ['cocomplete'],
	'finite products': ['products'],
	'finite coproducts': ['coproducts'],
	'binary products': ['finite products'],
	'binary coproducts': ['finite coproducts'],
	'countable products': ['products', 'finite products'],
	'countable coproducts': ['coproducts', 'finite coproducts'],
	'equalizers': [],
	'coequalizers': [],
	'filtered limits': ['complete'],
	'filtered colimits': ['cocomplete'],
	'sequential limits': ['filtered limits'],
	'sequential colimits': ['filtered colimits'],
	'connected limits': ['connected', 'complete', 'filtered limits'],
	'connected colimits': ['connected', 'cocomplete', 'filtered colimits'],
	'strict initial object': ['initial object'],
	'strict terminal object': ['terminal object'],
	'self-dual': [],
	'groupoid': [],
	'essentially small': ['small'],
	'thin': [],
	'discrete': ['essentially discrete'],
	'essentially discrete': ['discrete'],
	'finitary algebraic': [],
	'finite': ['essentially finite'],
	'essentially finite': ['finite'],
	'connected': [],
	'pullbacks': ['wide pullbacks'],
	'pushouts': [],
	'trivial': [],
	'inhabited': [],
	'subobject classifier': ['elementary topos'],
	'balanced': [],
	'infinitary distributive': ['distributive'],
	'distributive': ['infinitary distributive'],
	'generator': [],
	'cogenerator': [],
	'exact filtered colimits': ['filtered colimits', 'finitely complete'],
	'Grothendieck abelian': ['abelian', 'cocomplete', 'generator', 'exact filtered colimits'],
	'disjoint finite coproducts': ['finite coproducts', 'disjoint coproducts'],
	'disjoint coproducts': ['coproducts', 'disjoint finite coproducts'],
	'left cancellative': ['groupoid'],
	'right cancellative': ['groupoid'],
	'wide pullbacks': ['pullbacks'],
	'wide pushouts': ['pushouts'],
	'split abelian': ['abelian'],
	'Cauchy complete': ['finitely complete'],
	'mono-regular': [],
	'epi-regular': [],
	'skeletal': [],
	'Malcev': ['finitely complete'],
}
