import type { PropertyID } from './properties.data'

export const PROPERTY_RELATIONS: Partial<Record<PropertyID, PropertyID[]>> = {
	'small': ['essentially small'],
	'locally small': ['locally essentially small'],
	'locally essentially small': ['locally small'],
	'cartesian closed': ['finite products'],
	'zero morphisms': ['preadditive', 'pointed'],
	'preadditive': ['additive'],
	'additive': ['preadditive', 'finite products'],
	'abelian': ['additive'],
	'finitely complete': ['complete'],
	'finitely cocomplete': ['cocomplete'],
	'pointed': ['initial object', 'terminal object'],
	'locally finitely presentable': ['locally presentable', 'locally ℵ₁-presentable'],
	'locally presentable': ['locally finitely presentable', 'locally ℵ₁-presentable'],
	'locally ℵ₁-presentable': ['locally finitely presentable', 'locally presentable'],
	'Grothendieck topos': ['elementary topos'],
	'finite products': ['products'],
	'finite coproducts': ['coproducts'],
	'binary products': ['finite products'],
	'binary coproducts': ['finite coproducts'],
	'countable products': ['products', 'finite products'],
	'countable coproducts': ['coproducts', 'finite coproducts'],
	'filtered limits': ['complete'],
	'filtered colimits': ['cocomplete'],
	'sequential limits': ['filtered limits'],
	'sequential colimits': ['filtered colimits'],
	'connected limits': ['connected', 'complete', 'filtered limits'],
	'connected colimits': ['connected', 'cocomplete', 'filtered colimits'],
	'strict initial object': ['initial object'],
	'strict terminal object': ['terminal object'],
	'essentially small': ['small'],
	'discrete': ['essentially discrete'],
	'essentially discrete': ['discrete'],
	'finite': ['essentially finite'],
	'essentially finite': ['finite'],
	'pullbacks': ['wide pullbacks'],
	'subobject classifier': ['elementary topos'],
	'infinitary distributive': ['distributive'],
	'distributive': ['infinitary distributive'],
	'exact filtered colimits': ['filtered colimits', 'finitely complete'],
	'Grothendieck abelian': ['abelian', 'cocomplete', 'generator', 'exact filtered colimits'],
	'disjoint finite coproducts': ['finite coproducts', 'disjoint coproducts'],
	'disjoint coproducts': ['coproducts', 'disjoint finite coproducts'],
	'wide pullbacks': ['pullbacks'],
	'wide pushouts': ['pushouts'],
	'split abelian': ['abelian'],
	'Cauchy complete': ['finitely complete'],
}
