/**
 * Dictionary of LaTeX macros
 */
export const MACROS = {
	'\\IN': '\\mathbb{N}',
	'\\IZ': '\\mathbb{Z}',
	'\\IQ': '\\mathbb{Q}',
	'\\IR': '\\mathbb{R}',
	'\\IC': '\\mathbb{C}',
	'\\IF': '\\mathbb{F}',
	'\\IB': '\\mathbb{B}',
	'\\IA': '\\mathbb{A}',
	'\\IP': '\\mathbb{P}',
	'\\Mor': '\\operatorname{Mor}',
	'\\Hom': '\\operatorname{Hom}',
	'\\End': '\\operatorname{End}',
	'\\Ob': '\\operatorname{Ob}',
	'\\id': '\\operatorname{id}',
	'\\A': '\\mathcal{A}',
	'\\B': '\\mathcal{B}',
	'\\C': '\\mathcal{C}',
	'\\D': '\\mathcal{D}',
	'\\E': '\\mathcal{E}',
	'\\F': '\\mathcal{F}',
	'\\I': '\\mathcal{I}',
	'\\J': '\\mathcal{J}',
	'\\O': '\\mathcal{O}',
	'\\S': '\\mathcal{S}',
	'\\op': '\\mathrm{op}',
	'\\c': '\\mathrm{c}',
	'\\f': '\\mathrm{f}',
	'\\fg': '\\mathrm{fg}',
	'\\fp': '\\mathrm{fp}',
	'\\ab': '\\mathrm{ab}',
	'\\reg': '\\mathrm{reg}',
	'\\card': '\\operatorname{card}',
	'\\colim': '\\operatorname{colim}',
	'\\im': '\\operatorname{im}',
	'\\lcm': '\\operatorname{lcm}',
	'\\Spec': '\\operatorname{Spec}',
	'\\Sh': '\\operatorname{Sh}',
	'\\ord': '\\operatorname{ord}',
	'\\diag': '\\operatorname{diag}',
	'\\Sub': '\\operatorname{Sub}',
	'\\Quot': '\\operatorname{Quot}',
	'\\supp': '\\operatorname{supp}',
}
