INSERT INTO related_properties (property_id, related_property_id)
VALUES
	('small', 'essentially small'),
	('locally small', 'locally essentially small'),
	('locally essentially small', 'locally small'),
	('cartesian closed', 'finite products'),
	('zero morphisms', 'preadditive'),
	('zero morphisms', 'pointed'),
	('preadditive', 'additive'),
	('additive', 'preadditive'),
	('additive', 'finite products'),
	('abelian', 'additive'),
	('finitely complete', 'complete'),
	('finitely cocomplete', 'cocomplete'),
	('pointed', 'initial object'),
	('pointed', 'terminal object'),
	('locally finitely presentable', 'locally presentable'),
	('locally finitely presentable', 'locally ℵ₁-presentable'),
	('locally presentable', 'locally finitely presentable'),
	('locally presentable', 'locally ℵ₁-presentable'),
	('locally ℵ₁-presentable', 'locally finitely presentable'),
	('locally ℵ₁-presentable', 'locally presentable'),
	('elementary topos', 'Grothendieck topos'),
	('Grothendieck topos', 'elementary topos'),
	('initial object', 'finite coproducts'),
	('terminal object', 'finite coproducts'),
	('products', 'complete'),
	('coproducts', 'cocomplete'),
	('finite products', 'products'),
	('finite coproducts', 'coproducts'),
	('binary products', 'finite products'),
	('binary coproducts', 'finite coproducts'),
	('countable products', 'products'),
	('countable products', 'finite products'),
	('countable coproducts', 'coproducts'),
	('countable coproducts', 'finite coproducts'),
	('filtered limits', 'complete'),
	('filtered colimits', 'cocomplete'),
	('sequential limits', 'filtered limits'),
	('sequential colimits', 'filtered colimits'),
	('connected limits', 'connected'),
	('connected limits', 'complete'),
	('connected limits', 'filtered limits'),
	('connected colimits', 'connected'),
	('connected colimits', 'cocomplete'),
	('connected colimits', 'filtered colimits'),
	('strict initial object', 'initial object'),
	('strict terminal object', 'terminal object'),
	('essentially small', 'small'),
	('discrete', 'essentially discrete'),
	('essentially discrete', 'discrete'),
	('finite', 'essentially finite'),
	('essentially finite', 'finite'),
	('pullbacks', 'wide pullbacks'),
	('subobject classifier', 'elementary topos'),
	('infinitary distributive', 'distributive'),
	('distributive', 'infinitary distributive'),
	('exact filtered colimits', 'filtered colimits'),
	('exact filtered colimits', 'finitely complete'),
	('Grothendieck abelian', 'abelian'),
	('Grothendieck abelian', 'cocomplete'),
	('Grothendieck abelian', 'generator'),
	('Grothendieck abelian', 'exact filtered colimits'),
	('disjoint finite coproducts', 'finite coproducts'),
	('disjoint finite coproducts', 'disjoint coproducts'),
	('disjoint coproducts', 'coproducts'),
	('disjoint coproducts', 'disjoint finite coproducts'),
	('left cancellative', 'groupoid'),
	('right cancellative', 'groupoid'),
	('wide pullbacks', 'pullbacks'),
	('wide pushouts', 'pushouts'),
	('split abelian', 'abelian'),
	('Cauchy complete', 'finitely complete'),
	('Malcev', 'finitely complete');