INSERT INTO category_properties (
	category_id,
	property_id,
	reason
)
VALUES
	(
		'Ban',
		'locally small',
		'There is a forgetful functor $\mathbf{Ban} \to \mathbf{Set}$ and $\mathbf{Set}$ is locally small.' 
	),
	(
		'Ban',
		'pointed',
		'The trivial Banach space $\{0\}$ is a zero object.'
	),
	(
		'Ban',
		'locally ℵ₁-presentable',
		'Example 1.48 in <a href="https://ncatlab.org/nlab/show/Locally+Presentable+and+Accessible+Categories" target="_blank">Adamek-Rosicky</a>.'
	),
	(
		'Ban',
		'disjoint coproducts',
		'This follows from the corresponding fact for vector spaces, since the coproduct is built from the direct sum of vector spaces (using the $1$-norm).'
	),
	(
		'Ban',
		'cogenerator',
		'Hahn-Banach shows that $\mathbb{C}$ is a cogenerator'
	),


	(
		'Meas',
		'locally small',
		'There is a forgetful functor $\mathbf{Meas} \to \mathbf{Set}$ and $\mathbf{Set}$ is locally small.'
	),
	(
		'Meas',
		'well-powered',
		'follows from the fact that monomorphisms are injective here'
	),
	(
		'Meas',
		'well-copowered',
		'follows from the fact that epimorphisms are surjective here'
	),
	(
		'Meas',
		'complete',
		'Take the limit of the underlying sets and take the smallest $\sigma$-algebra making all projections measurable.'
	),
	(
		'Meas',
		'cocomplete',
		'Take the colimit of the underlying sets and take the largest $\sigma$-algebra making all inclusions measurable. That is, a set is measurable iff its preimage under each inclusion is measurable.'
	),
	(
		'Meas',
		'infinitary distributive',
		'We need to check that the canonical bijective measurable map $\coprod_i X \times Y_i \to X \times \coprod_i Y_i$ maps measurable sets onto measurable sets. By the description of measurable sets in a disjoint union, it suffices to prove that each $X \times Y_i \to X \times \coprod_i Y_i$ maps measurable sets onto measurable sets. So it suffices to prove that $f : X \times Y \to X \times (Y + Z)$ does that. Using that $f$ is injective and that $f(X \times Y)$ is measurable, it follows that the subsets of $X \times Y$ that are mapped to a measurable set via $f$ form a $\sigma$-algebra. But the $\sigma$-algebra of $X \times Y$ is generated by sets of the form $U \times V$ for measurable subsets $U,V$, and their $f$-images are clearly measurable.'
	),
	(
		'Meas',
		'generator',
		'The one-point measurable space (with the unique $\sigma$-algebra) is a generator since it represents the forgetful functor $\mathbf{Meas} \to \mathbf{Set}$.'
	),
	(
		'Meas',
		'cogenerator',
		'Take the two-element set $2$ endowed with the trivial $\sigma$-algebra (where only $\emptyset$ and $2$ are measurable), and use that $2$ is a cogenerator for $\mathbf{Set}$.'
	),
	(
		'Meas',
		'disjoint coproducts',
		'This follows easily from the corresponding fact for sets, since coproducts are built using disjoint unions here.'
	),
	(
		'Cat',
		'locally small',
		'There is a forgetful functor $\mathbf{Cat} \to \mathbf{Set} \times \mathbf{Set}$, $\mathcal{C} \mapsto (\mathrm{Ob}(\mathcal{C}),\mathrm{Mor}(\mathcal{C}))$, and $\mathbf{Set} \times \mathbf{Set}$ is locally small.'
	),
	(
		'Cat',
		'cartesian closed',
		'See p. 98 in <a href="https://ncatlab.org/nlab/show/Categories+for+the+Working+Mathematician" target="_blank">Mac Lane</a>.'
	),
	(
		'Cat',
		'locally finitely presentable',
		'See <a href="https://mathoverflow.net/questions/84460" target="_blank">MO/84460</a>.'
	),
	(
		'Cat',
		'disjoint coproducts',
		'This follows easily from the description of a coproduct of categories (based on disjoint unions).'
	),
	(
		'Fld',
		'locally small',
		'There is a forgetful functor $\mathbf{Fld} \to \mathbf{Set}$ and $\mathbf{Set}$ is locally small.'
	),
	(
		'Fld',
		'filtered colimits',
		'Consider a filtered diagram $(F_i)$ of fields and take the colimit $F$ in the category of commutative rings. Now one checks that $F$ is a field as well, and the universal property remains true for fields.'
	),
	(
		'Fld',
		'connected limits',
		'Consider a connected diagram $(F_i)$ of fields and take the limit $F$ in the category of commutative rings. Now one checks that $F$ is a field as well, and the universal property remains true for fields. Namely, $1 = 0$ in $F$ would imply that $1 = 0$ in each $F_i$ and hence, since the diagram is connected, in some $F_i$, which is a contradiction. And if $x \in F$ is non-zero, then all components $x_i$ are non-zero and hence invertible: Choose some $j$ such that $x_j$ is non-zero. Since there is a zig zag path of morphisms between $i$ and $j$ in the index category, which get mapped to field homomorphisms which are injective, it follows that $x_i$ is non-zero.'
	),
	(
		'Fld',
		'inhabited',
		'trivial'
	),
	(
		'Fld',
		'left cancellative',
		'It is well-known that every field homomorphism is injective and hence a monomorphism.'
	),
	(
		'Fld',
		'well-powered',
		'The subfields of a given field form a set.'
	),

	(
		'FinOrd',
		'essentially small',
		'Every finite order is isomorphic to $\{1 < \cdots < n \}$ for some $n \in \mathbb{N}$.'
	),
	(
		'FinOrd',
		'locally small',
		'There is a forgetful functor $\mathbf{FinOrd} \to \mathbf{Set}$ and $\mathbf{Set}$ is locally small.'
	),
	(
		'FinOrd',
		'finitely complete',
		NULL
	),
	(
		'FinOrd',
		'generator',
		'The one-point finite order is a generator since it represents the forgetful functor $\mathbf{FinOrd} \to \mathbf{Set}$.'
	),
	(
		'FinOrd',
		'cogenerator',
		NULL
	),
	(
		'FinOrd',
		'strict initial object',
		'The empty order is initial and is clearly strict.'
	),
	(
		'FinOrd',
		'coequalizers',
		NULL
	),
	(
		'FinOrd',
		'mono-regular',
		NULL
	),
	(
		'FinOrd',
		'epi-regular',
		NULL
	),

	(
		'Sp',
		'essentially small',
		'This holds because $\mathbf{FinSet}$ and $\mathbb{B}$ are essentially small.'
	),
	(
		'Sp',
		'finitely complete',
		'This follows from the corresponding fact for $\mathbf{FinSet}$.'
	),
	(
		'Sp',
		'finitely cocomplete',
		'This follows from the corresponding fact for $\mathbf{FinSet}$.'
	),
	(
		'Sp',
		'mono-regular',
		'This follows from the corresponding fact for $\mathbf{FinSet}$ since there every monomorphism is even effective.'
	),
	(
		'Sp',
		'epi-regular',
		'This follows from the corresponding fact for $\mathbf{FinSet}$ since there every epiomorphism is even effective.'
	),
	(
		'Sp',
		'distributive',
		'This follows from the corresponding fact for $\mathbf{FinSet}$.'
	),
	(
		'Sp',
		'disjoint finite coproducts',
		'This follows from the corresponding fact for $\mathbf{FinSet}$.'
	);