INSERT INTO category_property_assignments (
	category_id,
	property_id,
	is_satisfied,
	reason
)
VALUES
(
	'FinOrd',
	'equalizers',
	TRUE,
	'Take the equalizer in $\FinSet$ and restrict the order.'
),
(
	'FinOrd',
	'generator',
	TRUE,
	'The one-point finite ordered set is a generator since it represents the forgetful functor $\FinOrd \to \Set$.'
),
(
	'FinOrd',
	'terminal object',
	TRUE,
	'Take the singleton set with the unique ordering.'
),
(
	'FinOrd',
	'cogenerator',
	TRUE,
	'The ordered set $\{0 < 1\}$ is a cogenerator, even for <a href="/category/Pos">the category of posets</a>, see there for a proof.'
),
(
	'FinOrd',
	'strict initial object',
	TRUE,
	'The empty ordered set is initial and is clearly strict.'
),
(
	'FinOrd',
	'coequalizers',
	TRUE,
	'It suffices to construct quotients by equivalence relations. Let $\sim$ be an equivalence relation on $X$, where $(X,\leq)$ is a finite ordered set. Since $X$ is finite, by induction we may assume that $\sim$ is generated by a single relation $(a,b)$. If $a=b$, there is nothing to prove. If $a < b$ and $X = \{0,1,\dotsc,n-1\}$ with the usual order, the quotient is $\{0,1,\dotsc,a,b+1,\dotsc,n-1\}$ with the usual order.'
),
(
	'FinOrd',
	'mono-regular',
	TRUE,
	'Let $i : A \to B$ be a monomorphism of finite ordered sets. If $A$ is empty, then $i$ is clearly regular, so assume it is not. The map $i$ is injective (see below), hence order-reflecting. Define maps $u,v  : B \to A$ by $u(b) := \max \{a \in A : i(a) \leq b \}$ and $v(b) := \min \{a \in A : b \leq i(a) \}$. These are order-preserving and satisfy $u \circ i = v \circ i$, both sides are $\id_A$. Conversely, if $b \in B$ satisfies $u(b) = v(b) =: a$, then $i(a) \leq b$ and $b \leq i(a)$, hence $b = i(a)$. This shows that $i$ is the equalizer of $u,v$.'
),
(
	'FinOrd',
	'epi-regular',
	TRUE,
	'Let $f : A \to B$ be an epimorphism of finite ordered sets. It is surjective (see below). Define $u,v : B \to A$ by $u(b) := \min(f^{-1}(b))$ and $v(b) := \max(f^{-1}(b))$. One can easily check that $u,v$ are order-preserving maps with $f \circ u = f \circ v$ (both sides are $\id_B$). Let $h : A \to T$ be an order-preserving map with $h \circ u = h \circ v$. Then $h(a)$ only depends on $b := f(a)$: We have $u(b) \leq a \leq v(b)$, hence $h(u(b)) \leq h(a) \leq h(v(b)) = h(u(b))$. Therefore, there is a unique map $\tilde{h} : B \to T$ with $\tilde{h}(f(a)) = h(a)$, and one easily checks that it is order-preserving. This shows that $f$ is the coequalizer of $u,v$.'
),
(
	'FinOrd',
	'semi-strongly connected',
	TRUE,
	'Every non-empty totally ordered set is weakly terminal (by using constant maps).'
),
(
	'FinOrd',
	'essentially countable',
	TRUE,
	'Every finite ordered set is isomorphic to $\{0 < \cdots < n-1 \}$ for some $n \in \IN$.'
),
(
	'FinOrd',
	'locally small',
	TRUE,
	'There is a forgetful functor $\FinOrd \to \Set$ and $\Set$ is locally small.'
),
(
	'FinOrd',
	'core-thin',
	TRUE,
	'Let $f : \{1 < \cdots < n \} \to \{1 < \cdots < n \}$ be an automorphism. Then $f(i)$ is the smallest element not contained in $\{f(j) : j < i\}$. From this one can deduce $f(i)=i$ by induction.'
),
(
	'FinOrd',
	'small',
	FALSE,
	'Even the collection of all singleton orders is not small.'
),
(
	'FinOrd',
	'strict terminal object',
	FALSE,
	'This is trivial.'
),
(
	'FinOrd',
	'sequential limits',
	FALSE,
	'Consider the (non-empty) ordered set $[n] := \{0 < \cdots < n\}$ for $n \in \IN$. The forgetful functor to $\Set$ is representable, hence preserves all limits. Thus, if the diagram of truncation maps $\cdots \twoheadrightarrow [2] \twoheadrightarrow [1] \twoheadrightarrow [0]$ has a limit in $\FinOrd$, its underlying set is isomorphic to the limit taken in $\Set$, which is $\IN \cup \{\infty\}$. But this is not a finite set.'
),
(
	'FinOrd',
	'sequential colimits',
	FALSE,
	'Consider the (non-empty) ordered set $[n] := \{0 < \cdots < n\}$ for $n \in \IN$. Assume the sequence of inclusion maps $[0] \hookrightarrow [1] \hookrightarrow [2] \hookrightarrow \cdots$ has a colimit $(f_n : [n] \to X)$ in $\FinOrd$. Let $n_0 \geq 0$ be fixed. I claim that $f_{n_0}$ is injective, which will then yield a contradiction by taking $n_0 \geq \card(X)$. For $n \geq 0$ define $g_n : [n] \to [n_0]$ as follows. For $n \leq n_0$ it is the inclusion, and for $n \geq n_0$ it is the surjection which keeps all elements of $[n_0]$ and maps all other elements to $n_0$. Observe that $g_n$ preserves the order and $g_{n+1} |_{[n]} = g_n$. Hence, there is a unique order-preserving map $g : X \to [n_0]$ with $g \circ f_n = g_n$ for all $n$. For $n = n_0$ this shows $g \circ f_{n_0} = \id_{[n_0]}$, and $f_{n_0}$ is injective.'
),
(
	'FinOrd',
	'skeletal',
	FALSE,
	'This is trivial.'
),
(
	'FinOrd',
	'one-way',
	FALSE,
	'There are three different order-preserving maps $\{0 < 1\} \to \{0 < 1\}$.'
),
(
	'FinOrd',
	'countable',
	FALSE,
	'This is trivial.'
);
