export const PROPERTY_IDs = [
	'small',
	'locally small',
	'locally essentially small',
	'complete',
	'cocomplete',
	'cartesian closed',
	'zero morphisms',
	'preadditive',
	'additive',
	'abelian',
	'finitely complete',
	'finitely cocomplete',
	'pointed',
	'locally finitely presentable',
	'locally presentable',
	'locally ℵ₁-presentable',
	'elementary topos',
	'Grothendieck topos',
	'well-powered',
	'well-copowered',
	'initial object',
	'terminal object',
	'products',
	'coproducts',
	'finite products',
	'finite coproducts',
	'binary products',
	'binary coproducts',
	'countable products',
	'countable coproducts',
	'equalizers',
	'coequalizers',
	'connected limits',
	'connected colimits',
	'filtered limits',
	'filtered colimits',
	'sequential limits',
	'sequential colimits',
	'strict initial object',
	'strict terminal object',
	'self-dual',
	'groupoid',
	'essentially small',
	'thin',
	'discrete',
	'essentially discrete',
	'finitary algebraic',
	'finite',
	'essentially finite',
	'connected',
	'pullbacks',
	'pushouts',
	'trivial',
	'inhabited',
	'subobject classifier',
	'balanced',
	'infinitary distributive',
	'distributive',
	'generator',
	'cogenerator',
	'exact filtered colimits',
	'Grothendieck abelian',
	'disjoint finite coproducts',
	'disjoint coproducts',
	'left cancellative',
	'right cancellative',
	'wide pullbacks',
	'wide pushouts',
	'split abelian',
	'Cauchy complete',
	'mono-regular',
	'epi-regular',
] as const

export type PropertyID = (typeof PROPERTY_IDs)[number]

export function is_valid_property(id: string): id is PropertyID {
	return PROPERTY_IDs.includes(id as PropertyID)
}
