name: preview deployment (without db update)
on:
    workflow_dispatch:

jobs:
    call-deploy:
        uses: ./.github/workflows/_deploy-reusable.yaml
        permissions:
            contents: write
        with:
            is_prod: false
            skip_db: true
        secrets:
            DB_URL: ${{ secrets.DB_PREVIEW_URL }}
            DB_AUTH_TOKEN: ${{ secrets.DB_PREVIEW_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
            DB_VISITS_URL: ${{ secrets.DB_VISITS_URL }}
            DB_VISITS_AUTH_TOKEN: ${{ secrets.DB_VISITS_AUTH_TOKEN }}
            _GITHUB_PRIVATE_KEY: ${{ secrets._GITHUB_PRIVATE_KEY }}
            REDIS_URL: ${{ secrets.REDIS_URL }}
            ADMIN_PAGE_PASSWORD: ${{ secrets.ADMIN_PAGE_PASSWORD }}
