name: production deployment
on:
    workflow_dispatch:

jobs:
    call-deploy:
        uses: ./.github/workflows/_deploy-reusable.yaml
        permissions:
            contents: write
        with:
            is_prod: true
        secrets: inherit
