name: preview deployment

on:
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Install pnpm
              uses: pnpm/action-setup@v5
              with:
                  version: 10

            - name: Use Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: 24.14.0
                  cache: 'pnpm'

            - name: Install Dependencies
              run: pnpm i

            - name: Generate SvelteKit config
              run: pnpm svelte-kit sync

            - name: Update database
              env:
                  DB_URL: ${{ secrets.DB_PREVIEW_URL }}
                  DB_AUTH_TOKEN: ${{ secrets.DB_PREVIEW_AUTH_TOKEN }}
              run: pnpm db:update

            - name: Build app
              env:
                  DB_URL: ${{ secrets.DB_PREVIEW_URL }}
                  DB_AUTH_TOKEN: ${{ secrets.DB_PREVIEW_AUTH_TOKEN }}
                  DB_HTTP_URL: ${{ secrets.DB_PREVIEW_HTTP_URL }}
                  DB_AUTH_TOKEN_HTTP: ${{ secrets.DB_PREVIEW_AUTH_TOKEN_HTTP }}
                  INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}
              run: pnpm build

            - name: Deploy to Netlify - Preview
              run: |
                  pnpm exec netlify deploy --no-build \
                    --dir build \
                    --site ${{ secrets.NETLIFY_SITE_ID }} \
                    --auth ${{ secrets.NETLIFY_ACCESS_TOKEN }} \
                    --message "${{ github.event.head_commit.message }}"
