name: test
on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.13.0]

        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Sync SvelteKit
              run: pnpm svelte-kit sync

            - name: Build the project
              run: pnpm build

            - name: Run tests
              run: pnpm test

            - name: Run svelte checker
              run: pnpm check
